// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClassProto.proto

package cyan.simple.protobuf.model.proto;

public final class ClassProto {
  private ClassProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClassesMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cyan.simple.protobuf.proto.ClassesMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
     */
    java.util.List<cyan.simple.protobuf.model.proto.ClassProto.ClassMessage> 
        getClassesList();
    /**
     * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
     */
    cyan.simple.protobuf.model.proto.ClassProto.ClassMessage getClasses(int index);
    /**
     * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
     */
    int getClassesCount();
    /**
     * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
     */
    java.util.List<? extends cyan.simple.protobuf.model.proto.ClassProto.ClassMessageOrBuilder> 
        getClassesOrBuilderList();
    /**
     * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
     */
    cyan.simple.protobuf.model.proto.ClassProto.ClassMessageOrBuilder getClassesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code cyan.simple.protobuf.proto.ClassesMessage}
   */
  public  static final class ClassesMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cyan.simple.protobuf.proto.ClassesMessage)
      ClassesMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClassesMessage.newBuilder() to construct.
    private ClassesMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClassesMessage() {
      classes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClassesMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                classes_ = new java.util.ArrayList<cyan.simple.protobuf.model.proto.ClassProto.ClassMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              classes_.add(
                  input.readMessage(cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          classes_ = java.util.Collections.unmodifiableList(classes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cyan.simple.protobuf.model.proto.ClassProto.internal_static_cyan_simple_protobuf_proto_ClassesMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cyan.simple.protobuf.model.proto.ClassProto.internal_static_cyan_simple_protobuf_proto_ClassesMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.class, cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.Builder.class);
    }

    public static final int CLASSES_FIELD_NUMBER = 1;
    private java.util.List<cyan.simple.protobuf.model.proto.ClassProto.ClassMessage> classes_;
    /**
     * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
     */
    public java.util.List<cyan.simple.protobuf.model.proto.ClassProto.ClassMessage> getClassesList() {
      return classes_;
    }
    /**
     * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
     */
    public java.util.List<? extends cyan.simple.protobuf.model.proto.ClassProto.ClassMessageOrBuilder> 
        getClassesOrBuilderList() {
      return classes_;
    }
    /**
     * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
     */
    public int getClassesCount() {
      return classes_.size();
    }
    /**
     * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
     */
    public cyan.simple.protobuf.model.proto.ClassProto.ClassMessage getClasses(int index) {
      return classes_.get(index);
    }
    /**
     * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
     */
    public cyan.simple.protobuf.model.proto.ClassProto.ClassMessageOrBuilder getClassesOrBuilder(
        int index) {
      return classes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < classes_.size(); i++) {
        output.writeMessage(1, classes_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < classes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, classes_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage)) {
        return super.equals(obj);
      }
      cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage other = (cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage) obj;

      boolean result = true;
      result = result && getClassesList()
          .equals(other.getClassesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getClassesCount() > 0) {
        hash = (37 * hash) + CLASSES_FIELD_NUMBER;
        hash = (53 * hash) + getClassesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cyan.simple.protobuf.proto.ClassesMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cyan.simple.protobuf.proto.ClassesMessage)
        cyan.simple.protobuf.model.proto.ClassProto.ClassesMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cyan.simple.protobuf.model.proto.ClassProto.internal_static_cyan_simple_protobuf_proto_ClassesMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cyan.simple.protobuf.model.proto.ClassProto.internal_static_cyan_simple_protobuf_proto_ClassesMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.class, cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.Builder.class);
      }

      // Construct using cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getClassesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (classesBuilder_ == null) {
          classes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          classesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cyan.simple.protobuf.model.proto.ClassProto.internal_static_cyan_simple_protobuf_proto_ClassesMessage_descriptor;
      }

      public cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage getDefaultInstanceForType() {
        return cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.getDefaultInstance();
      }

      public cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage build() {
        cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage buildPartial() {
        cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage result = new cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage(this);
        int from_bitField0_ = bitField0_;
        if (classesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            classes_ = java.util.Collections.unmodifiableList(classes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.classes_ = classes_;
        } else {
          result.classes_ = classesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage) {
          return mergeFrom((cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage other) {
        if (other == cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.getDefaultInstance()) return this;
        if (classesBuilder_ == null) {
          if (!other.classes_.isEmpty()) {
            if (classes_.isEmpty()) {
              classes_ = other.classes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureClassesIsMutable();
              classes_.addAll(other.classes_);
            }
            onChanged();
          }
        } else {
          if (!other.classes_.isEmpty()) {
            if (classesBuilder_.isEmpty()) {
              classesBuilder_.dispose();
              classesBuilder_ = null;
              classes_ = other.classes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              classesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getClassesFieldBuilder() : null;
            } else {
              classesBuilder_.addAllMessages(other.classes_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<cyan.simple.protobuf.model.proto.ClassProto.ClassMessage> classes_ =
        java.util.Collections.emptyList();
      private void ensureClassesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          classes_ = new java.util.ArrayList<cyan.simple.protobuf.model.proto.ClassProto.ClassMessage>(classes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cyan.simple.protobuf.model.proto.ClassProto.ClassMessage, cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.Builder, cyan.simple.protobuf.model.proto.ClassProto.ClassMessageOrBuilder> classesBuilder_;

      /**
       * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
       */
      public java.util.List<cyan.simple.protobuf.model.proto.ClassProto.ClassMessage> getClassesList() {
        if (classesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(classes_);
        } else {
          return classesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
       */
      public int getClassesCount() {
        if (classesBuilder_ == null) {
          return classes_.size();
        } else {
          return classesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
       */
      public cyan.simple.protobuf.model.proto.ClassProto.ClassMessage getClasses(int index) {
        if (classesBuilder_ == null) {
          return classes_.get(index);
        } else {
          return classesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
       */
      public Builder setClasses(
          int index, cyan.simple.protobuf.model.proto.ClassProto.ClassMessage value) {
        if (classesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClassesIsMutable();
          classes_.set(index, value);
          onChanged();
        } else {
          classesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
       */
      public Builder setClasses(
          int index, cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.Builder builderForValue) {
        if (classesBuilder_ == null) {
          ensureClassesIsMutable();
          classes_.set(index, builderForValue.build());
          onChanged();
        } else {
          classesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
       */
      public Builder addClasses(cyan.simple.protobuf.model.proto.ClassProto.ClassMessage value) {
        if (classesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClassesIsMutable();
          classes_.add(value);
          onChanged();
        } else {
          classesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
       */
      public Builder addClasses(
          int index, cyan.simple.protobuf.model.proto.ClassProto.ClassMessage value) {
        if (classesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClassesIsMutable();
          classes_.add(index, value);
          onChanged();
        } else {
          classesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
       */
      public Builder addClasses(
          cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.Builder builderForValue) {
        if (classesBuilder_ == null) {
          ensureClassesIsMutable();
          classes_.add(builderForValue.build());
          onChanged();
        } else {
          classesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
       */
      public Builder addClasses(
          int index, cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.Builder builderForValue) {
        if (classesBuilder_ == null) {
          ensureClassesIsMutable();
          classes_.add(index, builderForValue.build());
          onChanged();
        } else {
          classesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
       */
      public Builder addAllClasses(
          java.lang.Iterable<? extends cyan.simple.protobuf.model.proto.ClassProto.ClassMessage> values) {
        if (classesBuilder_ == null) {
          ensureClassesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, classes_);
          onChanged();
        } else {
          classesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
       */
      public Builder clearClasses() {
        if (classesBuilder_ == null) {
          classes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          classesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
       */
      public Builder removeClasses(int index) {
        if (classesBuilder_ == null) {
          ensureClassesIsMutable();
          classes_.remove(index);
          onChanged();
        } else {
          classesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
       */
      public cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.Builder getClassesBuilder(
          int index) {
        return getClassesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
       */
      public cyan.simple.protobuf.model.proto.ClassProto.ClassMessageOrBuilder getClassesOrBuilder(
          int index) {
        if (classesBuilder_ == null) {
          return classes_.get(index);  } else {
          return classesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
       */
      public java.util.List<? extends cyan.simple.protobuf.model.proto.ClassProto.ClassMessageOrBuilder> 
           getClassesOrBuilderList() {
        if (classesBuilder_ != null) {
          return classesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(classes_);
        }
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
       */
      public cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.Builder addClassesBuilder() {
        return getClassesFieldBuilder().addBuilder(
            cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
       */
      public cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.Builder addClassesBuilder(
          int index) {
        return getClassesFieldBuilder().addBuilder(
            index, cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.ClassMessage classes = 1;</code>
       */
      public java.util.List<cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.Builder> 
           getClassesBuilderList() {
        return getClassesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cyan.simple.protobuf.model.proto.ClassProto.ClassMessage, cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.Builder, cyan.simple.protobuf.model.proto.ClassProto.ClassMessageOrBuilder> 
          getClassesFieldBuilder() {
        if (classesBuilder_ == null) {
          classesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cyan.simple.protobuf.model.proto.ClassProto.ClassMessage, cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.Builder, cyan.simple.protobuf.model.proto.ClassProto.ClassMessageOrBuilder>(
                  classes_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          classes_ = null;
        }
        return classesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cyan.simple.protobuf.proto.ClassesMessage)
    }

    // @@protoc_insertion_point(class_scope:cyan.simple.protobuf.proto.ClassesMessage)
    private static final cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage();
    }

    public static cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClassesMessage>
        PARSER = new com.google.protobuf.AbstractParser<ClassesMessage>() {
      public ClassesMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ClassesMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClassesMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClassesMessage> getParserForType() {
      return PARSER;
    }

    public cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClassMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cyan.simple.protobuf.proto.ClassMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 班级名称
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     * 班级名称
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 班级人数
     * </pre>
     *
     * <code>int32 size = 2;</code>
     */
    int getSize();

    /**
     * <pre>
     * 教师列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
     */
    java.util.List<cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage> 
        getTeachersList();
    /**
     * <pre>
     * 教师列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
     */
    cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage getTeachers(int index);
    /**
     * <pre>
     * 教师列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
     */
    int getTeachersCount();
    /**
     * <pre>
     * 教师列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
     */
    java.util.List<? extends cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder> 
        getTeachersOrBuilderList();
    /**
     * <pre>
     * 教师列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
     */
    cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder getTeachersOrBuilder(
        int index);

    /**
     * <pre>
     * 学生列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
     */
    java.util.List<cyan.simple.protobuf.model.proto.StudentProto.StudentMessage> 
        getStudentsList();
    /**
     * <pre>
     * 学生列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
     */
    cyan.simple.protobuf.model.proto.StudentProto.StudentMessage getStudents(int index);
    /**
     * <pre>
     * 学生列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
     */
    int getStudentsCount();
    /**
     * <pre>
     * 学生列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
     */
    java.util.List<? extends cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder> 
        getStudentsOrBuilderList();
    /**
     * <pre>
     * 学生列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
     */
    cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder getStudentsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code cyan.simple.protobuf.proto.ClassMessage}
   */
  public  static final class ClassMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cyan.simple.protobuf.proto.ClassMessage)
      ClassMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClassMessage.newBuilder() to construct.
    private ClassMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClassMessage() {
      name_ = "";
      size_ = 0;
      teachers_ = java.util.Collections.emptyList();
      students_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClassMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              size_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                teachers_ = new java.util.ArrayList<cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage>();
                mutable_bitField0_ |= 0x00000004;
              }
              teachers_.add(
                  input.readMessage(cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.parser(), extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                students_ = new java.util.ArrayList<cyan.simple.protobuf.model.proto.StudentProto.StudentMessage>();
                mutable_bitField0_ |= 0x00000008;
              }
              students_.add(
                  input.readMessage(cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          teachers_ = java.util.Collections.unmodifiableList(teachers_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          students_ = java.util.Collections.unmodifiableList(students_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cyan.simple.protobuf.model.proto.ClassProto.internal_static_cyan_simple_protobuf_proto_ClassMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cyan.simple.protobuf.model.proto.ClassProto.internal_static_cyan_simple_protobuf_proto_ClassMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.class, cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * 班级名称
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 班级名称
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIZE_FIELD_NUMBER = 2;
    private int size_;
    /**
     * <pre>
     * 班级人数
     * </pre>
     *
     * <code>int32 size = 2;</code>
     */
    public int getSize() {
      return size_;
    }

    public static final int TEACHERS_FIELD_NUMBER = 3;
    private java.util.List<cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage> teachers_;
    /**
     * <pre>
     * 教师列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
     */
    public java.util.List<cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage> getTeachersList() {
      return teachers_;
    }
    /**
     * <pre>
     * 教师列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
     */
    public java.util.List<? extends cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder> 
        getTeachersOrBuilderList() {
      return teachers_;
    }
    /**
     * <pre>
     * 教师列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
     */
    public int getTeachersCount() {
      return teachers_.size();
    }
    /**
     * <pre>
     * 教师列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
     */
    public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage getTeachers(int index) {
      return teachers_.get(index);
    }
    /**
     * <pre>
     * 教师列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
     */
    public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder getTeachersOrBuilder(
        int index) {
      return teachers_.get(index);
    }

    public static final int STUDENTS_FIELD_NUMBER = 4;
    private java.util.List<cyan.simple.protobuf.model.proto.StudentProto.StudentMessage> students_;
    /**
     * <pre>
     * 学生列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
     */
    public java.util.List<cyan.simple.protobuf.model.proto.StudentProto.StudentMessage> getStudentsList() {
      return students_;
    }
    /**
     * <pre>
     * 学生列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
     */
    public java.util.List<? extends cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder> 
        getStudentsOrBuilderList() {
      return students_;
    }
    /**
     * <pre>
     * 学生列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
     */
    public int getStudentsCount() {
      return students_.size();
    }
    /**
     * <pre>
     * 学生列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
     */
    public cyan.simple.protobuf.model.proto.StudentProto.StudentMessage getStudents(int index) {
      return students_.get(index);
    }
    /**
     * <pre>
     * 学生列表
     * </pre>
     *
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
     */
    public cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder getStudentsOrBuilder(
        int index) {
      return students_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (size_ != 0) {
        output.writeInt32(2, size_);
      }
      for (int i = 0; i < teachers_.size(); i++) {
        output.writeMessage(3, teachers_.get(i));
      }
      for (int i = 0; i < students_.size(); i++) {
        output.writeMessage(4, students_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (size_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, size_);
      }
      for (int i = 0; i < teachers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, teachers_.get(i));
      }
      for (int i = 0; i < students_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, students_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cyan.simple.protobuf.model.proto.ClassProto.ClassMessage)) {
        return super.equals(obj);
      }
      cyan.simple.protobuf.model.proto.ClassProto.ClassMessage other = (cyan.simple.protobuf.model.proto.ClassProto.ClassMessage) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getSize()
          == other.getSize());
      result = result && getTeachersList()
          .equals(other.getTeachersList());
      result = result && getStudentsList()
          .equals(other.getStudentsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
      if (getTeachersCount() > 0) {
        hash = (37 * hash) + TEACHERS_FIELD_NUMBER;
        hash = (53 * hash) + getTeachersList().hashCode();
      }
      if (getStudentsCount() > 0) {
        hash = (37 * hash) + STUDENTS_FIELD_NUMBER;
        hash = (53 * hash) + getStudentsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cyan.simple.protobuf.model.proto.ClassProto.ClassMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.ClassProto.ClassMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cyan.simple.protobuf.model.proto.ClassProto.ClassMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cyan.simple.protobuf.proto.ClassMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cyan.simple.protobuf.proto.ClassMessage)
        cyan.simple.protobuf.model.proto.ClassProto.ClassMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cyan.simple.protobuf.model.proto.ClassProto.internal_static_cyan_simple_protobuf_proto_ClassMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cyan.simple.protobuf.model.proto.ClassProto.internal_static_cyan_simple_protobuf_proto_ClassMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.class, cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.Builder.class);
      }

      // Construct using cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTeachersFieldBuilder();
          getStudentsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        size_ = 0;

        if (teachersBuilder_ == null) {
          teachers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          teachersBuilder_.clear();
        }
        if (studentsBuilder_ == null) {
          students_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          studentsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cyan.simple.protobuf.model.proto.ClassProto.internal_static_cyan_simple_protobuf_proto_ClassMessage_descriptor;
      }

      public cyan.simple.protobuf.model.proto.ClassProto.ClassMessage getDefaultInstanceForType() {
        return cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.getDefaultInstance();
      }

      public cyan.simple.protobuf.model.proto.ClassProto.ClassMessage build() {
        cyan.simple.protobuf.model.proto.ClassProto.ClassMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cyan.simple.protobuf.model.proto.ClassProto.ClassMessage buildPartial() {
        cyan.simple.protobuf.model.proto.ClassProto.ClassMessage result = new cyan.simple.protobuf.model.proto.ClassProto.ClassMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        result.size_ = size_;
        if (teachersBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            teachers_ = java.util.Collections.unmodifiableList(teachers_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.teachers_ = teachers_;
        } else {
          result.teachers_ = teachersBuilder_.build();
        }
        if (studentsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            students_ = java.util.Collections.unmodifiableList(students_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.students_ = students_;
        } else {
          result.students_ = studentsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cyan.simple.protobuf.model.proto.ClassProto.ClassMessage) {
          return mergeFrom((cyan.simple.protobuf.model.proto.ClassProto.ClassMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cyan.simple.protobuf.model.proto.ClassProto.ClassMessage other) {
        if (other == cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getSize() != 0) {
          setSize(other.getSize());
        }
        if (teachersBuilder_ == null) {
          if (!other.teachers_.isEmpty()) {
            if (teachers_.isEmpty()) {
              teachers_ = other.teachers_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureTeachersIsMutable();
              teachers_.addAll(other.teachers_);
            }
            onChanged();
          }
        } else {
          if (!other.teachers_.isEmpty()) {
            if (teachersBuilder_.isEmpty()) {
              teachersBuilder_.dispose();
              teachersBuilder_ = null;
              teachers_ = other.teachers_;
              bitField0_ = (bitField0_ & ~0x00000004);
              teachersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTeachersFieldBuilder() : null;
            } else {
              teachersBuilder_.addAllMessages(other.teachers_);
            }
          }
        }
        if (studentsBuilder_ == null) {
          if (!other.students_.isEmpty()) {
            if (students_.isEmpty()) {
              students_ = other.students_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureStudentsIsMutable();
              students_.addAll(other.students_);
            }
            onChanged();
          }
        } else {
          if (!other.students_.isEmpty()) {
            if (studentsBuilder_.isEmpty()) {
              studentsBuilder_.dispose();
              studentsBuilder_ = null;
              students_ = other.students_;
              bitField0_ = (bitField0_ & ~0x00000008);
              studentsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStudentsFieldBuilder() : null;
            } else {
              studentsBuilder_.addAllMessages(other.students_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cyan.simple.protobuf.model.proto.ClassProto.ClassMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cyan.simple.protobuf.model.proto.ClassProto.ClassMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * 班级名称
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 班级名称
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 班级名称
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 班级名称
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 班级名称
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int size_ ;
      /**
       * <pre>
       * 班级人数
       * </pre>
       *
       * <code>int32 size = 2;</code>
       */
      public int getSize() {
        return size_;
      }
      /**
       * <pre>
       * 班级人数
       * </pre>
       *
       * <code>int32 size = 2;</code>
       */
      public Builder setSize(int value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 班级人数
       * </pre>
       *
       * <code>int32 size = 2;</code>
       */
      public Builder clearSize() {
        
        size_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage> teachers_ =
        java.util.Collections.emptyList();
      private void ensureTeachersIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          teachers_ = new java.util.ArrayList<cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage>(teachers_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder> teachersBuilder_;

      /**
       * <pre>
       * 教师列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
       */
      public java.util.List<cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage> getTeachersList() {
        if (teachersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(teachers_);
        } else {
          return teachersBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 教师列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
       */
      public int getTeachersCount() {
        if (teachersBuilder_ == null) {
          return teachers_.size();
        } else {
          return teachersBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 教师列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
       */
      public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage getTeachers(int index) {
        if (teachersBuilder_ == null) {
          return teachers_.get(index);
        } else {
          return teachersBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 教师列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
       */
      public Builder setTeachers(
          int index, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage value) {
        if (teachersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeachersIsMutable();
          teachers_.set(index, value);
          onChanged();
        } else {
          teachersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 教师列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
       */
      public Builder setTeachers(
          int index, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder builderForValue) {
        if (teachersBuilder_ == null) {
          ensureTeachersIsMutable();
          teachers_.set(index, builderForValue.build());
          onChanged();
        } else {
          teachersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 教师列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
       */
      public Builder addTeachers(cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage value) {
        if (teachersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeachersIsMutable();
          teachers_.add(value);
          onChanged();
        } else {
          teachersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 教师列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
       */
      public Builder addTeachers(
          int index, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage value) {
        if (teachersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeachersIsMutable();
          teachers_.add(index, value);
          onChanged();
        } else {
          teachersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 教师列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
       */
      public Builder addTeachers(
          cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder builderForValue) {
        if (teachersBuilder_ == null) {
          ensureTeachersIsMutable();
          teachers_.add(builderForValue.build());
          onChanged();
        } else {
          teachersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 教师列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
       */
      public Builder addTeachers(
          int index, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder builderForValue) {
        if (teachersBuilder_ == null) {
          ensureTeachersIsMutable();
          teachers_.add(index, builderForValue.build());
          onChanged();
        } else {
          teachersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 教师列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
       */
      public Builder addAllTeachers(
          java.lang.Iterable<? extends cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage> values) {
        if (teachersBuilder_ == null) {
          ensureTeachersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, teachers_);
          onChanged();
        } else {
          teachersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 教师列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
       */
      public Builder clearTeachers() {
        if (teachersBuilder_ == null) {
          teachers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          teachersBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 教师列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
       */
      public Builder removeTeachers(int index) {
        if (teachersBuilder_ == null) {
          ensureTeachersIsMutable();
          teachers_.remove(index);
          onChanged();
        } else {
          teachersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 教师列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
       */
      public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder getTeachersBuilder(
          int index) {
        return getTeachersFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 教师列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
       */
      public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder getTeachersOrBuilder(
          int index) {
        if (teachersBuilder_ == null) {
          return teachers_.get(index);  } else {
          return teachersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 教师列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
       */
      public java.util.List<? extends cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder> 
           getTeachersOrBuilderList() {
        if (teachersBuilder_ != null) {
          return teachersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(teachers_);
        }
      }
      /**
       * <pre>
       * 教师列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
       */
      public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder addTeachersBuilder() {
        return getTeachersFieldBuilder().addBuilder(
            cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.getDefaultInstance());
      }
      /**
       * <pre>
       * 教师列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
       */
      public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder addTeachersBuilder(
          int index) {
        return getTeachersFieldBuilder().addBuilder(
            index, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.getDefaultInstance());
      }
      /**
       * <pre>
       * 教师列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 3;</code>
       */
      public java.util.List<cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder> 
           getTeachersBuilderList() {
        return getTeachersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder> 
          getTeachersFieldBuilder() {
        if (teachersBuilder_ == null) {
          teachersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder>(
                  teachers_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          teachers_ = null;
        }
        return teachersBuilder_;
      }

      private java.util.List<cyan.simple.protobuf.model.proto.StudentProto.StudentMessage> students_ =
        java.util.Collections.emptyList();
      private void ensureStudentsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          students_ = new java.util.ArrayList<cyan.simple.protobuf.model.proto.StudentProto.StudentMessage>(students_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cyan.simple.protobuf.model.proto.StudentProto.StudentMessage, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder, cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder> studentsBuilder_;

      /**
       * <pre>
       * 学生列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
       */
      public java.util.List<cyan.simple.protobuf.model.proto.StudentProto.StudentMessage> getStudentsList() {
        if (studentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(students_);
        } else {
          return studentsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 学生列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
       */
      public int getStudentsCount() {
        if (studentsBuilder_ == null) {
          return students_.size();
        } else {
          return studentsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 学生列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
       */
      public cyan.simple.protobuf.model.proto.StudentProto.StudentMessage getStudents(int index) {
        if (studentsBuilder_ == null) {
          return students_.get(index);
        } else {
          return studentsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 学生列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
       */
      public Builder setStudents(
          int index, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.set(index, value);
          onChanged();
        } else {
          studentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 学生列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
       */
      public Builder setStudents(
          int index, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.set(index, builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 学生列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
       */
      public Builder addStudents(cyan.simple.protobuf.model.proto.StudentProto.StudentMessage value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.add(value);
          onChanged();
        } else {
          studentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 学生列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
       */
      public Builder addStudents(
          int index, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.add(index, value);
          onChanged();
        } else {
          studentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 学生列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
       */
      public Builder addStudents(
          cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.add(builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 学生列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
       */
      public Builder addStudents(
          int index, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.add(index, builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 学生列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
       */
      public Builder addAllStudents(
          java.lang.Iterable<? extends cyan.simple.protobuf.model.proto.StudentProto.StudentMessage> values) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, students_);
          onChanged();
        } else {
          studentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 学生列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
       */
      public Builder clearStudents() {
        if (studentsBuilder_ == null) {
          students_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          studentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 学生列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
       */
      public Builder removeStudents(int index) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.remove(index);
          onChanged();
        } else {
          studentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 学生列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
       */
      public cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder getStudentsBuilder(
          int index) {
        return getStudentsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 学生列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
       */
      public cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder getStudentsOrBuilder(
          int index) {
        if (studentsBuilder_ == null) {
          return students_.get(index);  } else {
          return studentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 学生列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
       */
      public java.util.List<? extends cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder> 
           getStudentsOrBuilderList() {
        if (studentsBuilder_ != null) {
          return studentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(students_);
        }
      }
      /**
       * <pre>
       * 学生列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
       */
      public cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder addStudentsBuilder() {
        return getStudentsFieldBuilder().addBuilder(
            cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.getDefaultInstance());
      }
      /**
       * <pre>
       * 学生列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
       */
      public cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder addStudentsBuilder(
          int index) {
        return getStudentsFieldBuilder().addBuilder(
            index, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.getDefaultInstance());
      }
      /**
       * <pre>
       * 学生列表
       * </pre>
       *
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 4;</code>
       */
      public java.util.List<cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder> 
           getStudentsBuilderList() {
        return getStudentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cyan.simple.protobuf.model.proto.StudentProto.StudentMessage, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder, cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder> 
          getStudentsFieldBuilder() {
        if (studentsBuilder_ == null) {
          studentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cyan.simple.protobuf.model.proto.StudentProto.StudentMessage, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder, cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder>(
                  students_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          students_ = null;
        }
        return studentsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cyan.simple.protobuf.proto.ClassMessage)
    }

    // @@protoc_insertion_point(class_scope:cyan.simple.protobuf.proto.ClassMessage)
    private static final cyan.simple.protobuf.model.proto.ClassProto.ClassMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cyan.simple.protobuf.model.proto.ClassProto.ClassMessage();
    }

    public static cyan.simple.protobuf.model.proto.ClassProto.ClassMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClassMessage>
        PARSER = new com.google.protobuf.AbstractParser<ClassMessage>() {
      public ClassMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ClassMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClassMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClassMessage> getParserForType() {
      return PARSER;
    }

    public cyan.simple.protobuf.model.proto.ClassProto.ClassMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cyan_simple_protobuf_proto_ClassesMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cyan_simple_protobuf_proto_ClassesMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cyan_simple_protobuf_proto_ClassMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cyan_simple_protobuf_proto_ClassMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ClassProto.proto\022\032cyan.simple.protobuf" +
      ".proto\032\022TeacherProto.proto\032\022StudentProto" +
      ".proto\"K\n\016ClassesMessage\0229\n\007classes\030\001 \003(" +
      "\0132(.cyan.simple.protobuf.proto.ClassMess" +
      "age\"\246\001\n\014ClassMessage\022\014\n\004name\030\001 \001(\t\022\014\n\004si" +
      "ze\030\002 \001(\005\022<\n\010teachers\030\003 \003(\0132*.cyan.simple" +
      ".protobuf.proto.TeacherMessage\022<\n\010studen" +
      "ts\030\004 \003(\0132*.cyan.simple.protobuf.proto.St" +
      "udentMessageB.\n cyan.simple.protobuf.mod" +
      "el.protoB\nClassProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cyan.simple.protobuf.model.proto.TeacherProto.getDescriptor(),
          cyan.simple.protobuf.model.proto.StudentProto.getDescriptor(),
        }, assigner);
    internal_static_cyan_simple_protobuf_proto_ClassesMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cyan_simple_protobuf_proto_ClassesMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cyan_simple_protobuf_proto_ClassesMessage_descriptor,
        new java.lang.String[] { "Classes", });
    internal_static_cyan_simple_protobuf_proto_ClassMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cyan_simple_protobuf_proto_ClassMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cyan_simple_protobuf_proto_ClassMessage_descriptor,
        new java.lang.String[] { "Name", "Size", "Teachers", "Students", });
    cyan.simple.protobuf.model.proto.TeacherProto.getDescriptor();
    cyan.simple.protobuf.model.proto.StudentProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
