// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FilterProto.proto

package cyan.simple.protobuf.model.proto;

public final class FilterProto {
  private FilterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FilterBodyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cyan.simple.protobuf.proto.FilterBodyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.cyan.simple.protobuf.proto.FilterMessage filter = 1;</code>
     */
    boolean hasFilter();
    /**
     * <code>.cyan.simple.protobuf.proto.FilterMessage filter = 1;</code>
     */
    cyan.simple.protobuf.model.proto.FilterProto.FilterMessage getFilter();
    /**
     * <code>.cyan.simple.protobuf.proto.FilterMessage filter = 1;</code>
     */
    cyan.simple.protobuf.model.proto.FilterProto.FilterMessageOrBuilder getFilterOrBuilder();

    public cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage.BodyCase getBodyCase();
  }
  /**
   * Protobuf type {@code cyan.simple.protobuf.proto.FilterBodyMessage}
   */
  public  static final class FilterBodyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cyan.simple.protobuf.proto.FilterBodyMessage)
      FilterBodyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FilterBodyMessage.newBuilder() to construct.
    private FilterBodyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FilterBodyMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FilterBodyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.Builder subBuilder = null;
              if (bodyCase_ == 1) {
                subBuilder = ((cyan.simple.protobuf.model.proto.FilterProto.FilterMessage) body_).toBuilder();
              }
              body_ =
                  input.readMessage(cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((cyan.simple.protobuf.model.proto.FilterProto.FilterMessage) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 1;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cyan.simple.protobuf.model.proto.FilterProto.internal_static_cyan_simple_protobuf_proto_FilterBodyMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cyan.simple.protobuf.model.proto.FilterProto.internal_static_cyan_simple_protobuf_proto_FilterBodyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage.class, cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage.Builder.class);
    }

    private int bodyCase_ = 0;
    private java.lang.Object body_;
    public enum BodyCase
        implements com.google.protobuf.Internal.EnumLite {
      FILTER(1),
      BODY_NOT_SET(0);
      private final int value;
      private BodyCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static BodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static BodyCase forNumber(int value) {
        switch (value) {
          case 1: return FILTER;
          case 0: return BODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public BodyCase
    getBodyCase() {
      return BodyCase.forNumber(
          bodyCase_);
    }

    public static final int FILTER_FIELD_NUMBER = 1;
    /**
     * <code>.cyan.simple.protobuf.proto.FilterMessage filter = 1;</code>
     */
    public boolean hasFilter() {
      return bodyCase_ == 1;
    }
    /**
     * <code>.cyan.simple.protobuf.proto.FilterMessage filter = 1;</code>
     */
    public cyan.simple.protobuf.model.proto.FilterProto.FilterMessage getFilter() {
      if (bodyCase_ == 1) {
         return (cyan.simple.protobuf.model.proto.FilterProto.FilterMessage) body_;
      }
      return cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.getDefaultInstance();
    }
    /**
     * <code>.cyan.simple.protobuf.proto.FilterMessage filter = 1;</code>
     */
    public cyan.simple.protobuf.model.proto.FilterProto.FilterMessageOrBuilder getFilterOrBuilder() {
      if (bodyCase_ == 1) {
         return (cyan.simple.protobuf.model.proto.FilterProto.FilterMessage) body_;
      }
      return cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bodyCase_ == 1) {
        output.writeMessage(1, (cyan.simple.protobuf.model.proto.FilterProto.FilterMessage) body_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bodyCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (cyan.simple.protobuf.model.proto.FilterProto.FilterMessage) body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage)) {
        return super.equals(obj);
      }
      cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage other = (cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage) obj;

      boolean result = true;
      result = result && getBodyCase().equals(
          other.getBodyCase());
      if (!result) return false;
      switch (bodyCase_) {
        case 1:
          result = result && getFilter()
              .equals(other.getFilter());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (bodyCase_) {
        case 1:
          hash = (37 * hash) + FILTER_FIELD_NUMBER;
          hash = (53 * hash) + getFilter().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cyan.simple.protobuf.proto.FilterBodyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cyan.simple.protobuf.proto.FilterBodyMessage)
        cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cyan.simple.protobuf.model.proto.FilterProto.internal_static_cyan_simple_protobuf_proto_FilterBodyMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cyan.simple.protobuf.model.proto.FilterProto.internal_static_cyan_simple_protobuf_proto_FilterBodyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage.class, cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage.Builder.class);
      }

      // Construct using cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        bodyCase_ = 0;
        body_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cyan.simple.protobuf.model.proto.FilterProto.internal_static_cyan_simple_protobuf_proto_FilterBodyMessage_descriptor;
      }

      public cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage getDefaultInstanceForType() {
        return cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage.getDefaultInstance();
      }

      public cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage build() {
        cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage buildPartial() {
        cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage result = new cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage(this);
        if (bodyCase_ == 1) {
          if (filterBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = filterBuilder_.build();
          }
        }
        result.bodyCase_ = bodyCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage) {
          return mergeFrom((cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage other) {
        if (other == cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage.getDefaultInstance()) return this;
        switch (other.getBodyCase()) {
          case FILTER: {
            mergeFilter(other.getFilter());
            break;
          }
          case BODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bodyCase_ = 0;
      private java.lang.Object body_;
      public BodyCase
          getBodyCase() {
        return BodyCase.forNumber(
            bodyCase_);
      }

      public Builder clearBody() {
        bodyCase_ = 0;
        body_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          cyan.simple.protobuf.model.proto.FilterProto.FilterMessage, cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.Builder, cyan.simple.protobuf.model.proto.FilterProto.FilterMessageOrBuilder> filterBuilder_;
      /**
       * <code>.cyan.simple.protobuf.proto.FilterMessage filter = 1;</code>
       */
      public boolean hasFilter() {
        return bodyCase_ == 1;
      }
      /**
       * <code>.cyan.simple.protobuf.proto.FilterMessage filter = 1;</code>
       */
      public cyan.simple.protobuf.model.proto.FilterProto.FilterMessage getFilter() {
        if (filterBuilder_ == null) {
          if (bodyCase_ == 1) {
            return (cyan.simple.protobuf.model.proto.FilterProto.FilterMessage) body_;
          }
          return cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.getDefaultInstance();
        } else {
          if (bodyCase_ == 1) {
            return filterBuilder_.getMessage();
          }
          return cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.cyan.simple.protobuf.proto.FilterMessage filter = 1;</code>
       */
      public Builder setFilter(cyan.simple.protobuf.model.proto.FilterProto.FilterMessage value) {
        if (filterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          filterBuilder_.setMessage(value);
        }
        bodyCase_ = 1;
        return this;
      }
      /**
       * <code>.cyan.simple.protobuf.proto.FilterMessage filter = 1;</code>
       */
      public Builder setFilter(
          cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.Builder builderForValue) {
        if (filterBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          filterBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 1;
        return this;
      }
      /**
       * <code>.cyan.simple.protobuf.proto.FilterMessage filter = 1;</code>
       */
      public Builder mergeFilter(cyan.simple.protobuf.model.proto.FilterProto.FilterMessage value) {
        if (filterBuilder_ == null) {
          if (bodyCase_ == 1 &&
              body_ != cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.getDefaultInstance()) {
            body_ = cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.newBuilder((cyan.simple.protobuf.model.proto.FilterProto.FilterMessage) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 1) {
            filterBuilder_.mergeFrom(value);
          }
          filterBuilder_.setMessage(value);
        }
        bodyCase_ = 1;
        return this;
      }
      /**
       * <code>.cyan.simple.protobuf.proto.FilterMessage filter = 1;</code>
       */
      public Builder clearFilter() {
        if (filterBuilder_ == null) {
          if (bodyCase_ == 1) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 1) {
            bodyCase_ = 0;
            body_ = null;
          }
          filterBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.cyan.simple.protobuf.proto.FilterMessage filter = 1;</code>
       */
      public cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.Builder getFilterBuilder() {
        return getFilterFieldBuilder().getBuilder();
      }
      /**
       * <code>.cyan.simple.protobuf.proto.FilterMessage filter = 1;</code>
       */
      public cyan.simple.protobuf.model.proto.FilterProto.FilterMessageOrBuilder getFilterOrBuilder() {
        if ((bodyCase_ == 1) && (filterBuilder_ != null)) {
          return filterBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 1) {
            return (cyan.simple.protobuf.model.proto.FilterProto.FilterMessage) body_;
          }
          return cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.cyan.simple.protobuf.proto.FilterMessage filter = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cyan.simple.protobuf.model.proto.FilterProto.FilterMessage, cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.Builder, cyan.simple.protobuf.model.proto.FilterProto.FilterMessageOrBuilder> 
          getFilterFieldBuilder() {
        if (filterBuilder_ == null) {
          if (!(bodyCase_ == 1)) {
            body_ = cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.getDefaultInstance();
          }
          filterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cyan.simple.protobuf.model.proto.FilterProto.FilterMessage, cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.Builder, cyan.simple.protobuf.model.proto.FilterProto.FilterMessageOrBuilder>(
                  (cyan.simple.protobuf.model.proto.FilterProto.FilterMessage) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 1;
        onChanged();;
        return filterBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cyan.simple.protobuf.proto.FilterBodyMessage)
    }

    // @@protoc_insertion_point(class_scope:cyan.simple.protobuf.proto.FilterBodyMessage)
    private static final cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage();
    }

    public static cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FilterBodyMessage>
        PARSER = new com.google.protobuf.AbstractParser<FilterBodyMessage>() {
      public FilterBodyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FilterBodyMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FilterBodyMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FilterBodyMessage> getParserForType() {
      return PARSER;
    }

    public cyan.simple.protobuf.model.proto.FilterProto.FilterBodyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FilterMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cyan.simple.protobuf.proto.FilterMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 根据名称查询
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     * 根据名称查询
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code cyan.simple.protobuf.proto.FilterMessage}
   */
  public  static final class FilterMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cyan.simple.protobuf.proto.FilterMessage)
      FilterMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FilterMessage.newBuilder() to construct.
    private FilterMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FilterMessage() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FilterMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cyan.simple.protobuf.model.proto.FilterProto.internal_static_cyan_simple_protobuf_proto_FilterMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cyan.simple.protobuf.model.proto.FilterProto.internal_static_cyan_simple_protobuf_proto_FilterMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.class, cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * 根据名称查询
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 根据名称查询
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cyan.simple.protobuf.model.proto.FilterProto.FilterMessage)) {
        return super.equals(obj);
      }
      cyan.simple.protobuf.model.proto.FilterProto.FilterMessage other = (cyan.simple.protobuf.model.proto.FilterProto.FilterMessage) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cyan.simple.protobuf.model.proto.FilterProto.FilterMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.FilterProto.FilterMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cyan.simple.protobuf.model.proto.FilterProto.FilterMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cyan.simple.protobuf.proto.FilterMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cyan.simple.protobuf.proto.FilterMessage)
        cyan.simple.protobuf.model.proto.FilterProto.FilterMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cyan.simple.protobuf.model.proto.FilterProto.internal_static_cyan_simple_protobuf_proto_FilterMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cyan.simple.protobuf.model.proto.FilterProto.internal_static_cyan_simple_protobuf_proto_FilterMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.class, cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.Builder.class);
      }

      // Construct using cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cyan.simple.protobuf.model.proto.FilterProto.internal_static_cyan_simple_protobuf_proto_FilterMessage_descriptor;
      }

      public cyan.simple.protobuf.model.proto.FilterProto.FilterMessage getDefaultInstanceForType() {
        return cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.getDefaultInstance();
      }

      public cyan.simple.protobuf.model.proto.FilterProto.FilterMessage build() {
        cyan.simple.protobuf.model.proto.FilterProto.FilterMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cyan.simple.protobuf.model.proto.FilterProto.FilterMessage buildPartial() {
        cyan.simple.protobuf.model.proto.FilterProto.FilterMessage result = new cyan.simple.protobuf.model.proto.FilterProto.FilterMessage(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cyan.simple.protobuf.model.proto.FilterProto.FilterMessage) {
          return mergeFrom((cyan.simple.protobuf.model.proto.FilterProto.FilterMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cyan.simple.protobuf.model.proto.FilterProto.FilterMessage other) {
        if (other == cyan.simple.protobuf.model.proto.FilterProto.FilterMessage.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cyan.simple.protobuf.model.proto.FilterProto.FilterMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cyan.simple.protobuf.model.proto.FilterProto.FilterMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * 根据名称查询
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 根据名称查询
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 根据名称查询
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 根据名称查询
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 根据名称查询
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cyan.simple.protobuf.proto.FilterMessage)
    }

    // @@protoc_insertion_point(class_scope:cyan.simple.protobuf.proto.FilterMessage)
    private static final cyan.simple.protobuf.model.proto.FilterProto.FilterMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cyan.simple.protobuf.model.proto.FilterProto.FilterMessage();
    }

    public static cyan.simple.protobuf.model.proto.FilterProto.FilterMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FilterMessage>
        PARSER = new com.google.protobuf.AbstractParser<FilterMessage>() {
      public FilterMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FilterMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FilterMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FilterMessage> getParserForType() {
      return PARSER;
    }

    public cyan.simple.protobuf.model.proto.FilterProto.FilterMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cyan_simple_protobuf_proto_FilterBodyMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cyan_simple_protobuf_proto_FilterBodyMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cyan_simple_protobuf_proto_FilterMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cyan_simple_protobuf_proto_FilterMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021FilterProto.proto\022\032cyan.simple.protobu" +
      "f.proto\"X\n\021FilterBodyMessage\022;\n\006filter\030\001" +
      " \001(\0132).cyan.simple.protobuf.proto.Filter" +
      "MessageH\000B\006\n\004body\"\035\n\rFilterMessage\022\014\n\004na" +
      "me\030\001 \001(\tB/\n cyan.simple.protobuf.model.p" +
      "rotoB\013FilterProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cyan_simple_protobuf_proto_FilterBodyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cyan_simple_protobuf_proto_FilterBodyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cyan_simple_protobuf_proto_FilterBodyMessage_descriptor,
        new java.lang.String[] { "Filter", "Body", });
    internal_static_cyan_simple_protobuf_proto_FilterMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cyan_simple_protobuf_proto_FilterMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cyan_simple_protobuf_proto_FilterMessage_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
