// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResultProto.proto

package cyan.simple.protobuf.model.proto;

public final class ResultProto {
  private ResultProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResultMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cyan.simple.protobuf.proto.ResultMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 状态码
     * </pre>
     *
     * <code>int32 status = 1;</code>
     */
    int getStatus();

    /**
     * <pre>
     * 信息
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * 信息
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     * 单个班级信息
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.ClassMessage class = 3;</code>
     */
    boolean hasClass_();
    /**
     * <pre>
     * 单个班级信息
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.ClassMessage class = 3;</code>
     */
    cyan.simple.protobuf.model.proto.ClassProto.ClassMessage getClass_();
    /**
     * <pre>
     * 单个班级信息
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.ClassMessage class = 3;</code>
     */
    cyan.simple.protobuf.model.proto.ClassProto.ClassMessageOrBuilder getClass_OrBuilder();

    /**
     * <pre>
     * 这里没办法直接写 repeated ClassMessage classes = 4;
     * 需要在外部包装一层对象
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.ClassesMessage classes = 4;</code>
     */
    boolean hasClasses();
    /**
     * <pre>
     * 这里没办法直接写 repeated ClassMessage classes = 4;
     * 需要在外部包装一层对象
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.ClassesMessage classes = 4;</code>
     */
    cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage getClasses();
    /**
     * <pre>
     * 这里没办法直接写 repeated ClassMessage classes = 4;
     * 需要在外部包装一层对象
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.ClassesMessage classes = 4;</code>
     */
    cyan.simple.protobuf.model.proto.ClassProto.ClassesMessageOrBuilder getClassesOrBuilder();

    /**
     * <pre>
     * 单个教师信息
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.TeacherMessage teacher = 5;</code>
     */
    boolean hasTeacher();
    /**
     * <pre>
     * 单个教师信息
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.TeacherMessage teacher = 5;</code>
     */
    cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage getTeacher();
    /**
     * <pre>
     * 单个教师信息
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.TeacherMessage teacher = 5;</code>
     */
    cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder getTeacherOrBuilder();

    /**
     * <pre>
     * 这里没办法直接写 repeated TeacherMessage teachers = 6;
     * 需要在外部包装一层对象
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.TeachersMessage teachers = 6;</code>
     */
    boolean hasTeachers();
    /**
     * <pre>
     * 这里没办法直接写 repeated TeacherMessage teachers = 6;
     * 需要在外部包装一层对象
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.TeachersMessage teachers = 6;</code>
     */
    cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage getTeachers();
    /**
     * <pre>
     * 这里没办法直接写 repeated TeacherMessage teachers = 6;
     * 需要在外部包装一层对象
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.TeachersMessage teachers = 6;</code>
     */
    cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessageOrBuilder getTeachersOrBuilder();

    /**
     * <pre>
     * 单个学生信息
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.StudentMessage student = 7;</code>
     */
    boolean hasStudent();
    /**
     * <pre>
     * 单个学生信息
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.StudentMessage student = 7;</code>
     */
    cyan.simple.protobuf.model.proto.StudentProto.StudentMessage getStudent();
    /**
     * <pre>
     * 单个学生信息
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.StudentMessage student = 7;</code>
     */
    cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder getStudentOrBuilder();

    /**
     * <pre>
     * 这里没办法直接写 repeated TeacherMessage teachers = 8;
     * 需要在外部包装一层对象
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.StudentsMessage students = 8;</code>
     */
    boolean hasStudents();
    /**
     * <pre>
     * 这里没办法直接写 repeated TeacherMessage teachers = 8;
     * 需要在外部包装一层对象
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.StudentsMessage students = 8;</code>
     */
    cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage getStudents();
    /**
     * <pre>
     * 这里没办法直接写 repeated TeacherMessage teachers = 8;
     * 需要在外部包装一层对象
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.StudentsMessage students = 8;</code>
     */
    cyan.simple.protobuf.model.proto.StudentProto.StudentsMessageOrBuilder getStudentsOrBuilder();

    /**
     * <pre>
     * 时间
     * </pre>
     *
     * <code>int64 timestamp = 9;</code>
     */
    long getTimestamp();

    public cyan.simple.protobuf.model.proto.ResultProto.ResultMessage.DataCase getDataCase();
  }
  /**
   * Protobuf type {@code cyan.simple.protobuf.proto.ResultMessage}
   */
  public  static final class ResultMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cyan.simple.protobuf.proto.ResultMessage)
      ResultMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResultMessage.newBuilder() to construct.
    private ResultMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResultMessage() {
      status_ = 0;
      message_ = "";
      timestamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResultMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              status_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 26: {
              cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.Builder subBuilder = null;
              if (dataCase_ == 3) {
                subBuilder = ((cyan.simple.protobuf.model.proto.ClassProto.ClassMessage) data_).toBuilder();
              }
              data_ =
                  input.readMessage(cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((cyan.simple.protobuf.model.proto.ClassProto.ClassMessage) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 3;
              break;
            }
            case 34: {
              cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.Builder subBuilder = null;
              if (dataCase_ == 4) {
                subBuilder = ((cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage) data_).toBuilder();
              }
              data_ =
                  input.readMessage(cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 4;
              break;
            }
            case 42: {
              cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder subBuilder = null;
              if (dataCase_ == 5) {
                subBuilder = ((cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage) data_).toBuilder();
              }
              data_ =
                  input.readMessage(cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 5;
              break;
            }
            case 50: {
              cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.Builder subBuilder = null;
              if (dataCase_ == 6) {
                subBuilder = ((cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage) data_).toBuilder();
              }
              data_ =
                  input.readMessage(cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 6;
              break;
            }
            case 58: {
              cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder subBuilder = null;
              if (dataCase_ == 7) {
                subBuilder = ((cyan.simple.protobuf.model.proto.StudentProto.StudentMessage) data_).toBuilder();
              }
              data_ =
                  input.readMessage(cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((cyan.simple.protobuf.model.proto.StudentProto.StudentMessage) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 7;
              break;
            }
            case 66: {
              cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.Builder subBuilder = null;
              if (dataCase_ == 8) {
                subBuilder = ((cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage) data_).toBuilder();
              }
              data_ =
                  input.readMessage(cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 8;
              break;
            }
            case 72: {

              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cyan.simple.protobuf.model.proto.ResultProto.internal_static_cyan_simple_protobuf_proto_ResultMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cyan.simple.protobuf.model.proto.ResultProto.internal_static_cyan_simple_protobuf_proto_ResultMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cyan.simple.protobuf.model.proto.ResultProto.ResultMessage.class, cyan.simple.protobuf.model.proto.ResultProto.ResultMessage.Builder.class);
    }

    private int dataCase_ = 0;
    private java.lang.Object data_;
    public enum DataCase
        implements com.google.protobuf.Internal.EnumLite {
      CLASS(3),
      CLASSES(4),
      TEACHER(5),
      TEACHERS(6),
      STUDENT(7),
      STUDENTS(8),
      DATA_NOT_SET(0);
      private final int value;
      private DataCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataCase forNumber(int value) {
        switch (value) {
          case 3: return CLASS;
          case 4: return CLASSES;
          case 5: return TEACHER;
          case 6: return TEACHERS;
          case 7: return STUDENT;
          case 8: return STUDENTS;
          case 0: return DATA_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataCase
    getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <pre>
     * 状态码
     * </pre>
     *
     * <code>int32 status = 1;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * 信息
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 信息
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLASS_FIELD_NUMBER = 3;
    /**
     * <pre>
     * 单个班级信息
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.ClassMessage class = 3;</code>
     */
    public boolean hasClass_() {
      return dataCase_ == 3;
    }
    /**
     * <pre>
     * 单个班级信息
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.ClassMessage class = 3;</code>
     */
    public cyan.simple.protobuf.model.proto.ClassProto.ClassMessage getClass_() {
      if (dataCase_ == 3) {
         return (cyan.simple.protobuf.model.proto.ClassProto.ClassMessage) data_;
      }
      return cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.getDefaultInstance();
    }
    /**
     * <pre>
     * 单个班级信息
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.ClassMessage class = 3;</code>
     */
    public cyan.simple.protobuf.model.proto.ClassProto.ClassMessageOrBuilder getClass_OrBuilder() {
      if (dataCase_ == 3) {
         return (cyan.simple.protobuf.model.proto.ClassProto.ClassMessage) data_;
      }
      return cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.getDefaultInstance();
    }

    public static final int CLASSES_FIELD_NUMBER = 4;
    /**
     * <pre>
     * 这里没办法直接写 repeated ClassMessage classes = 4;
     * 需要在外部包装一层对象
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.ClassesMessage classes = 4;</code>
     */
    public boolean hasClasses() {
      return dataCase_ == 4;
    }
    /**
     * <pre>
     * 这里没办法直接写 repeated ClassMessage classes = 4;
     * 需要在外部包装一层对象
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.ClassesMessage classes = 4;</code>
     */
    public cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage getClasses() {
      if (dataCase_ == 4) {
         return (cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage) data_;
      }
      return cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.getDefaultInstance();
    }
    /**
     * <pre>
     * 这里没办法直接写 repeated ClassMessage classes = 4;
     * 需要在外部包装一层对象
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.ClassesMessage classes = 4;</code>
     */
    public cyan.simple.protobuf.model.proto.ClassProto.ClassesMessageOrBuilder getClassesOrBuilder() {
      if (dataCase_ == 4) {
         return (cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage) data_;
      }
      return cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.getDefaultInstance();
    }

    public static final int TEACHER_FIELD_NUMBER = 5;
    /**
     * <pre>
     * 单个教师信息
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.TeacherMessage teacher = 5;</code>
     */
    public boolean hasTeacher() {
      return dataCase_ == 5;
    }
    /**
     * <pre>
     * 单个教师信息
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.TeacherMessage teacher = 5;</code>
     */
    public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage getTeacher() {
      if (dataCase_ == 5) {
         return (cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage) data_;
      }
      return cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.getDefaultInstance();
    }
    /**
     * <pre>
     * 单个教师信息
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.TeacherMessage teacher = 5;</code>
     */
    public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder getTeacherOrBuilder() {
      if (dataCase_ == 5) {
         return (cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage) data_;
      }
      return cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.getDefaultInstance();
    }

    public static final int TEACHERS_FIELD_NUMBER = 6;
    /**
     * <pre>
     * 这里没办法直接写 repeated TeacherMessage teachers = 6;
     * 需要在外部包装一层对象
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.TeachersMessage teachers = 6;</code>
     */
    public boolean hasTeachers() {
      return dataCase_ == 6;
    }
    /**
     * <pre>
     * 这里没办法直接写 repeated TeacherMessage teachers = 6;
     * 需要在外部包装一层对象
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.TeachersMessage teachers = 6;</code>
     */
    public cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage getTeachers() {
      if (dataCase_ == 6) {
         return (cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage) data_;
      }
      return cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.getDefaultInstance();
    }
    /**
     * <pre>
     * 这里没办法直接写 repeated TeacherMessage teachers = 6;
     * 需要在外部包装一层对象
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.TeachersMessage teachers = 6;</code>
     */
    public cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessageOrBuilder getTeachersOrBuilder() {
      if (dataCase_ == 6) {
         return (cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage) data_;
      }
      return cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.getDefaultInstance();
    }

    public static final int STUDENT_FIELD_NUMBER = 7;
    /**
     * <pre>
     * 单个学生信息
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.StudentMessage student = 7;</code>
     */
    public boolean hasStudent() {
      return dataCase_ == 7;
    }
    /**
     * <pre>
     * 单个学生信息
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.StudentMessage student = 7;</code>
     */
    public cyan.simple.protobuf.model.proto.StudentProto.StudentMessage getStudent() {
      if (dataCase_ == 7) {
         return (cyan.simple.protobuf.model.proto.StudentProto.StudentMessage) data_;
      }
      return cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.getDefaultInstance();
    }
    /**
     * <pre>
     * 单个学生信息
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.StudentMessage student = 7;</code>
     */
    public cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder getStudentOrBuilder() {
      if (dataCase_ == 7) {
         return (cyan.simple.protobuf.model.proto.StudentProto.StudentMessage) data_;
      }
      return cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.getDefaultInstance();
    }

    public static final int STUDENTS_FIELD_NUMBER = 8;
    /**
     * <pre>
     * 这里没办法直接写 repeated TeacherMessage teachers = 8;
     * 需要在外部包装一层对象
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.StudentsMessage students = 8;</code>
     */
    public boolean hasStudents() {
      return dataCase_ == 8;
    }
    /**
     * <pre>
     * 这里没办法直接写 repeated TeacherMessage teachers = 8;
     * 需要在外部包装一层对象
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.StudentsMessage students = 8;</code>
     */
    public cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage getStudents() {
      if (dataCase_ == 8) {
         return (cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage) data_;
      }
      return cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.getDefaultInstance();
    }
    /**
     * <pre>
     * 这里没办法直接写 repeated TeacherMessage teachers = 8;
     * 需要在外部包装一层对象
     * </pre>
     *
     * <code>.cyan.simple.protobuf.proto.StudentsMessage students = 8;</code>
     */
    public cyan.simple.protobuf.model.proto.StudentProto.StudentsMessageOrBuilder getStudentsOrBuilder() {
      if (dataCase_ == 8) {
         return (cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage) data_;
      }
      return cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.getDefaultInstance();
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 9;
    private long timestamp_;
    /**
     * <pre>
     * 时间
     * </pre>
     *
     * <code>int64 timestamp = 9;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != 0) {
        output.writeInt32(1, status_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (dataCase_ == 3) {
        output.writeMessage(3, (cyan.simple.protobuf.model.proto.ClassProto.ClassMessage) data_);
      }
      if (dataCase_ == 4) {
        output.writeMessage(4, (cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage) data_);
      }
      if (dataCase_ == 5) {
        output.writeMessage(5, (cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage) data_);
      }
      if (dataCase_ == 6) {
        output.writeMessage(6, (cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage) data_);
      }
      if (dataCase_ == 7) {
        output.writeMessage(7, (cyan.simple.protobuf.model.proto.StudentProto.StudentMessage) data_);
      }
      if (dataCase_ == 8) {
        output.writeMessage(8, (cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage) data_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(9, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (dataCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (cyan.simple.protobuf.model.proto.ClassProto.ClassMessage) data_);
      }
      if (dataCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage) data_);
      }
      if (dataCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage) data_);
      }
      if (dataCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, (cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage) data_);
      }
      if (dataCase_ == 7) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, (cyan.simple.protobuf.model.proto.StudentProto.StudentMessage) data_);
      }
      if (dataCase_ == 8) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, (cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage) data_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cyan.simple.protobuf.model.proto.ResultProto.ResultMessage)) {
        return super.equals(obj);
      }
      cyan.simple.protobuf.model.proto.ResultProto.ResultMessage other = (cyan.simple.protobuf.model.proto.ResultProto.ResultMessage) obj;

      boolean result = true;
      result = result && (getStatus()
          == other.getStatus());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getDataCase().equals(
          other.getDataCase());
      if (!result) return false;
      switch (dataCase_) {
        case 3:
          result = result && getClass_()
              .equals(other.getClass_());
          break;
        case 4:
          result = result && getClasses()
              .equals(other.getClasses());
          break;
        case 5:
          result = result && getTeacher()
              .equals(other.getTeacher());
          break;
        case 6:
          result = result && getTeachers()
              .equals(other.getTeachers());
          break;
        case 7:
          result = result && getStudent()
              .equals(other.getStudent());
          break;
        case 8:
          result = result && getStudents()
              .equals(other.getStudents());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      switch (dataCase_) {
        case 3:
          hash = (37 * hash) + CLASS_FIELD_NUMBER;
          hash = (53 * hash) + getClass_().hashCode();
          break;
        case 4:
          hash = (37 * hash) + CLASSES_FIELD_NUMBER;
          hash = (53 * hash) + getClasses().hashCode();
          break;
        case 5:
          hash = (37 * hash) + TEACHER_FIELD_NUMBER;
          hash = (53 * hash) + getTeacher().hashCode();
          break;
        case 6:
          hash = (37 * hash) + TEACHERS_FIELD_NUMBER;
          hash = (53 * hash) + getTeachers().hashCode();
          break;
        case 7:
          hash = (37 * hash) + STUDENT_FIELD_NUMBER;
          hash = (53 * hash) + getStudent().hashCode();
          break;
        case 8:
          hash = (37 * hash) + STUDENTS_FIELD_NUMBER;
          hash = (53 * hash) + getStudents().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cyan.simple.protobuf.model.proto.ResultProto.ResultMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.ResultProto.ResultMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.ResultProto.ResultMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.ResultProto.ResultMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.ResultProto.ResultMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.ResultProto.ResultMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.ResultProto.ResultMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.ResultProto.ResultMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.ResultProto.ResultMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.ResultProto.ResultMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.ResultProto.ResultMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.ResultProto.ResultMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cyan.simple.protobuf.model.proto.ResultProto.ResultMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cyan.simple.protobuf.proto.ResultMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cyan.simple.protobuf.proto.ResultMessage)
        cyan.simple.protobuf.model.proto.ResultProto.ResultMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cyan.simple.protobuf.model.proto.ResultProto.internal_static_cyan_simple_protobuf_proto_ResultMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cyan.simple.protobuf.model.proto.ResultProto.internal_static_cyan_simple_protobuf_proto_ResultMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cyan.simple.protobuf.model.proto.ResultProto.ResultMessage.class, cyan.simple.protobuf.model.proto.ResultProto.ResultMessage.Builder.class);
      }

      // Construct using cyan.simple.protobuf.model.proto.ResultProto.ResultMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        status_ = 0;

        message_ = "";

        timestamp_ = 0L;

        dataCase_ = 0;
        data_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cyan.simple.protobuf.model.proto.ResultProto.internal_static_cyan_simple_protobuf_proto_ResultMessage_descriptor;
      }

      public cyan.simple.protobuf.model.proto.ResultProto.ResultMessage getDefaultInstanceForType() {
        return cyan.simple.protobuf.model.proto.ResultProto.ResultMessage.getDefaultInstance();
      }

      public cyan.simple.protobuf.model.proto.ResultProto.ResultMessage build() {
        cyan.simple.protobuf.model.proto.ResultProto.ResultMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cyan.simple.protobuf.model.proto.ResultProto.ResultMessage buildPartial() {
        cyan.simple.protobuf.model.proto.ResultProto.ResultMessage result = new cyan.simple.protobuf.model.proto.ResultProto.ResultMessage(this);
        result.status_ = status_;
        result.message_ = message_;
        if (dataCase_ == 3) {
          if (class_Builder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = class_Builder_.build();
          }
        }
        if (dataCase_ == 4) {
          if (classesBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = classesBuilder_.build();
          }
        }
        if (dataCase_ == 5) {
          if (teacherBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = teacherBuilder_.build();
          }
        }
        if (dataCase_ == 6) {
          if (teachersBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = teachersBuilder_.build();
          }
        }
        if (dataCase_ == 7) {
          if (studentBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = studentBuilder_.build();
          }
        }
        if (dataCase_ == 8) {
          if (studentsBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = studentsBuilder_.build();
          }
        }
        result.timestamp_ = timestamp_;
        result.dataCase_ = dataCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cyan.simple.protobuf.model.proto.ResultProto.ResultMessage) {
          return mergeFrom((cyan.simple.protobuf.model.proto.ResultProto.ResultMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cyan.simple.protobuf.model.proto.ResultProto.ResultMessage other) {
        if (other == cyan.simple.protobuf.model.proto.ResultProto.ResultMessage.getDefaultInstance()) return this;
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        switch (other.getDataCase()) {
          case CLASS: {
            mergeClass_(other.getClass_());
            break;
          }
          case CLASSES: {
            mergeClasses(other.getClasses());
            break;
          }
          case TEACHER: {
            mergeTeacher(other.getTeacher());
            break;
          }
          case TEACHERS: {
            mergeTeachers(other.getTeachers());
            break;
          }
          case STUDENT: {
            mergeStudent(other.getStudent());
            break;
          }
          case STUDENTS: {
            mergeStudents(other.getStudents());
            break;
          }
          case DATA_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cyan.simple.protobuf.model.proto.ResultProto.ResultMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cyan.simple.protobuf.model.proto.ResultProto.ResultMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataCase_ = 0;
      private java.lang.Object data_;
      public DataCase
          getDataCase() {
        return DataCase.forNumber(
            dataCase_);
      }

      public Builder clearData() {
        dataCase_ = 0;
        data_ = null;
        onChanged();
        return this;
      }


      private int status_ ;
      /**
       * <pre>
       * 状态码
       * </pre>
       *
       * <code>int32 status = 1;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <pre>
       * 状态码
       * </pre>
       *
       * <code>int32 status = 1;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态码
       * </pre>
       *
       * <code>int32 status = 1;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * 信息
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 信息
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 信息
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 信息
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 信息
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          cyan.simple.protobuf.model.proto.ClassProto.ClassMessage, cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.Builder, cyan.simple.protobuf.model.proto.ClassProto.ClassMessageOrBuilder> class_Builder_;
      /**
       * <pre>
       * 单个班级信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.ClassMessage class = 3;</code>
       */
      public boolean hasClass_() {
        return dataCase_ == 3;
      }
      /**
       * <pre>
       * 单个班级信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.ClassMessage class = 3;</code>
       */
      public cyan.simple.protobuf.model.proto.ClassProto.ClassMessage getClass_() {
        if (class_Builder_ == null) {
          if (dataCase_ == 3) {
            return (cyan.simple.protobuf.model.proto.ClassProto.ClassMessage) data_;
          }
          return cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.getDefaultInstance();
        } else {
          if (dataCase_ == 3) {
            return class_Builder_.getMessage();
          }
          return cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 单个班级信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.ClassMessage class = 3;</code>
       */
      public Builder setClass_(cyan.simple.protobuf.model.proto.ClassProto.ClassMessage value) {
        if (class_Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          class_Builder_.setMessage(value);
        }
        dataCase_ = 3;
        return this;
      }
      /**
       * <pre>
       * 单个班级信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.ClassMessage class = 3;</code>
       */
      public Builder setClass_(
          cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.Builder builderForValue) {
        if (class_Builder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          class_Builder_.setMessage(builderForValue.build());
        }
        dataCase_ = 3;
        return this;
      }
      /**
       * <pre>
       * 单个班级信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.ClassMessage class = 3;</code>
       */
      public Builder mergeClass_(cyan.simple.protobuf.model.proto.ClassProto.ClassMessage value) {
        if (class_Builder_ == null) {
          if (dataCase_ == 3 &&
              data_ != cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.getDefaultInstance()) {
            data_ = cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.newBuilder((cyan.simple.protobuf.model.proto.ClassProto.ClassMessage) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 3) {
            class_Builder_.mergeFrom(value);
          }
          class_Builder_.setMessage(value);
        }
        dataCase_ = 3;
        return this;
      }
      /**
       * <pre>
       * 单个班级信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.ClassMessage class = 3;</code>
       */
      public Builder clearClass_() {
        if (class_Builder_ == null) {
          if (dataCase_ == 3) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 3) {
            dataCase_ = 0;
            data_ = null;
          }
          class_Builder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 单个班级信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.ClassMessage class = 3;</code>
       */
      public cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.Builder getClass_Builder() {
        return getClass_FieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 单个班级信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.ClassMessage class = 3;</code>
       */
      public cyan.simple.protobuf.model.proto.ClassProto.ClassMessageOrBuilder getClass_OrBuilder() {
        if ((dataCase_ == 3) && (class_Builder_ != null)) {
          return class_Builder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 3) {
            return (cyan.simple.protobuf.model.proto.ClassProto.ClassMessage) data_;
          }
          return cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 单个班级信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.ClassMessage class = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cyan.simple.protobuf.model.proto.ClassProto.ClassMessage, cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.Builder, cyan.simple.protobuf.model.proto.ClassProto.ClassMessageOrBuilder> 
          getClass_FieldBuilder() {
        if (class_Builder_ == null) {
          if (!(dataCase_ == 3)) {
            data_ = cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.getDefaultInstance();
          }
          class_Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cyan.simple.protobuf.model.proto.ClassProto.ClassMessage, cyan.simple.protobuf.model.proto.ClassProto.ClassMessage.Builder, cyan.simple.protobuf.model.proto.ClassProto.ClassMessageOrBuilder>(
                  (cyan.simple.protobuf.model.proto.ClassProto.ClassMessage) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 3;
        onChanged();;
        return class_Builder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage, cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.Builder, cyan.simple.protobuf.model.proto.ClassProto.ClassesMessageOrBuilder> classesBuilder_;
      /**
       * <pre>
       * 这里没办法直接写 repeated ClassMessage classes = 4;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.ClassesMessage classes = 4;</code>
       */
      public boolean hasClasses() {
        return dataCase_ == 4;
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated ClassMessage classes = 4;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.ClassesMessage classes = 4;</code>
       */
      public cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage getClasses() {
        if (classesBuilder_ == null) {
          if (dataCase_ == 4) {
            return (cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage) data_;
          }
          return cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.getDefaultInstance();
        } else {
          if (dataCase_ == 4) {
            return classesBuilder_.getMessage();
          }
          return cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated ClassMessage classes = 4;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.ClassesMessage classes = 4;</code>
       */
      public Builder setClasses(cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage value) {
        if (classesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          classesBuilder_.setMessage(value);
        }
        dataCase_ = 4;
        return this;
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated ClassMessage classes = 4;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.ClassesMessage classes = 4;</code>
       */
      public Builder setClasses(
          cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.Builder builderForValue) {
        if (classesBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          classesBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 4;
        return this;
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated ClassMessage classes = 4;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.ClassesMessage classes = 4;</code>
       */
      public Builder mergeClasses(cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage value) {
        if (classesBuilder_ == null) {
          if (dataCase_ == 4 &&
              data_ != cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.getDefaultInstance()) {
            data_ = cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.newBuilder((cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 4) {
            classesBuilder_.mergeFrom(value);
          }
          classesBuilder_.setMessage(value);
        }
        dataCase_ = 4;
        return this;
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated ClassMessage classes = 4;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.ClassesMessage classes = 4;</code>
       */
      public Builder clearClasses() {
        if (classesBuilder_ == null) {
          if (dataCase_ == 4) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 4) {
            dataCase_ = 0;
            data_ = null;
          }
          classesBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated ClassMessage classes = 4;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.ClassesMessage classes = 4;</code>
       */
      public cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.Builder getClassesBuilder() {
        return getClassesFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated ClassMessage classes = 4;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.ClassesMessage classes = 4;</code>
       */
      public cyan.simple.protobuf.model.proto.ClassProto.ClassesMessageOrBuilder getClassesOrBuilder() {
        if ((dataCase_ == 4) && (classesBuilder_ != null)) {
          return classesBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 4) {
            return (cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage) data_;
          }
          return cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated ClassMessage classes = 4;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.ClassesMessage classes = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage, cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.Builder, cyan.simple.protobuf.model.proto.ClassProto.ClassesMessageOrBuilder> 
          getClassesFieldBuilder() {
        if (classesBuilder_ == null) {
          if (!(dataCase_ == 4)) {
            data_ = cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.getDefaultInstance();
          }
          classesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage, cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage.Builder, cyan.simple.protobuf.model.proto.ClassProto.ClassesMessageOrBuilder>(
                  (cyan.simple.protobuf.model.proto.ClassProto.ClassesMessage) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 4;
        onChanged();;
        return classesBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder> teacherBuilder_;
      /**
       * <pre>
       * 单个教师信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.TeacherMessage teacher = 5;</code>
       */
      public boolean hasTeacher() {
        return dataCase_ == 5;
      }
      /**
       * <pre>
       * 单个教师信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.TeacherMessage teacher = 5;</code>
       */
      public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage getTeacher() {
        if (teacherBuilder_ == null) {
          if (dataCase_ == 5) {
            return (cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage) data_;
          }
          return cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.getDefaultInstance();
        } else {
          if (dataCase_ == 5) {
            return teacherBuilder_.getMessage();
          }
          return cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 单个教师信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.TeacherMessage teacher = 5;</code>
       */
      public Builder setTeacher(cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage value) {
        if (teacherBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          teacherBuilder_.setMessage(value);
        }
        dataCase_ = 5;
        return this;
      }
      /**
       * <pre>
       * 单个教师信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.TeacherMessage teacher = 5;</code>
       */
      public Builder setTeacher(
          cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder builderForValue) {
        if (teacherBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          teacherBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 5;
        return this;
      }
      /**
       * <pre>
       * 单个教师信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.TeacherMessage teacher = 5;</code>
       */
      public Builder mergeTeacher(cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage value) {
        if (teacherBuilder_ == null) {
          if (dataCase_ == 5 &&
              data_ != cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.getDefaultInstance()) {
            data_ = cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.newBuilder((cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 5) {
            teacherBuilder_.mergeFrom(value);
          }
          teacherBuilder_.setMessage(value);
        }
        dataCase_ = 5;
        return this;
      }
      /**
       * <pre>
       * 单个教师信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.TeacherMessage teacher = 5;</code>
       */
      public Builder clearTeacher() {
        if (teacherBuilder_ == null) {
          if (dataCase_ == 5) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 5) {
            dataCase_ = 0;
            data_ = null;
          }
          teacherBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 单个教师信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.TeacherMessage teacher = 5;</code>
       */
      public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder getTeacherBuilder() {
        return getTeacherFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 单个教师信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.TeacherMessage teacher = 5;</code>
       */
      public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder getTeacherOrBuilder() {
        if ((dataCase_ == 5) && (teacherBuilder_ != null)) {
          return teacherBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 5) {
            return (cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage) data_;
          }
          return cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 单个教师信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.TeacherMessage teacher = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder> 
          getTeacherFieldBuilder() {
        if (teacherBuilder_ == null) {
          if (!(dataCase_ == 5)) {
            data_ = cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.getDefaultInstance();
          }
          teacherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder>(
                  (cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 5;
        onChanged();;
        return teacherBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage, cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.Builder, cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessageOrBuilder> teachersBuilder_;
      /**
       * <pre>
       * 这里没办法直接写 repeated TeacherMessage teachers = 6;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.TeachersMessage teachers = 6;</code>
       */
      public boolean hasTeachers() {
        return dataCase_ == 6;
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated TeacherMessage teachers = 6;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.TeachersMessage teachers = 6;</code>
       */
      public cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage getTeachers() {
        if (teachersBuilder_ == null) {
          if (dataCase_ == 6) {
            return (cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage) data_;
          }
          return cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.getDefaultInstance();
        } else {
          if (dataCase_ == 6) {
            return teachersBuilder_.getMessage();
          }
          return cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated TeacherMessage teachers = 6;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.TeachersMessage teachers = 6;</code>
       */
      public Builder setTeachers(cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage value) {
        if (teachersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          teachersBuilder_.setMessage(value);
        }
        dataCase_ = 6;
        return this;
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated TeacherMessage teachers = 6;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.TeachersMessage teachers = 6;</code>
       */
      public Builder setTeachers(
          cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.Builder builderForValue) {
        if (teachersBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          teachersBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 6;
        return this;
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated TeacherMessage teachers = 6;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.TeachersMessage teachers = 6;</code>
       */
      public Builder mergeTeachers(cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage value) {
        if (teachersBuilder_ == null) {
          if (dataCase_ == 6 &&
              data_ != cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.getDefaultInstance()) {
            data_ = cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.newBuilder((cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 6) {
            teachersBuilder_.mergeFrom(value);
          }
          teachersBuilder_.setMessage(value);
        }
        dataCase_ = 6;
        return this;
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated TeacherMessage teachers = 6;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.TeachersMessage teachers = 6;</code>
       */
      public Builder clearTeachers() {
        if (teachersBuilder_ == null) {
          if (dataCase_ == 6) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 6) {
            dataCase_ = 0;
            data_ = null;
          }
          teachersBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated TeacherMessage teachers = 6;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.TeachersMessage teachers = 6;</code>
       */
      public cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.Builder getTeachersBuilder() {
        return getTeachersFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated TeacherMessage teachers = 6;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.TeachersMessage teachers = 6;</code>
       */
      public cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessageOrBuilder getTeachersOrBuilder() {
        if ((dataCase_ == 6) && (teachersBuilder_ != null)) {
          return teachersBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 6) {
            return (cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage) data_;
          }
          return cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated TeacherMessage teachers = 6;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.TeachersMessage teachers = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage, cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.Builder, cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessageOrBuilder> 
          getTeachersFieldBuilder() {
        if (teachersBuilder_ == null) {
          if (!(dataCase_ == 6)) {
            data_ = cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.getDefaultInstance();
          }
          teachersBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage, cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.Builder, cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessageOrBuilder>(
                  (cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 6;
        onChanged();;
        return teachersBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          cyan.simple.protobuf.model.proto.StudentProto.StudentMessage, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder, cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder> studentBuilder_;
      /**
       * <pre>
       * 单个学生信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.StudentMessage student = 7;</code>
       */
      public boolean hasStudent() {
        return dataCase_ == 7;
      }
      /**
       * <pre>
       * 单个学生信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.StudentMessage student = 7;</code>
       */
      public cyan.simple.protobuf.model.proto.StudentProto.StudentMessage getStudent() {
        if (studentBuilder_ == null) {
          if (dataCase_ == 7) {
            return (cyan.simple.protobuf.model.proto.StudentProto.StudentMessage) data_;
          }
          return cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.getDefaultInstance();
        } else {
          if (dataCase_ == 7) {
            return studentBuilder_.getMessage();
          }
          return cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 单个学生信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.StudentMessage student = 7;</code>
       */
      public Builder setStudent(cyan.simple.protobuf.model.proto.StudentProto.StudentMessage value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          studentBuilder_.setMessage(value);
        }
        dataCase_ = 7;
        return this;
      }
      /**
       * <pre>
       * 单个学生信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.StudentMessage student = 7;</code>
       */
      public Builder setStudent(
          cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder builderForValue) {
        if (studentBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          studentBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 7;
        return this;
      }
      /**
       * <pre>
       * 单个学生信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.StudentMessage student = 7;</code>
       */
      public Builder mergeStudent(cyan.simple.protobuf.model.proto.StudentProto.StudentMessage value) {
        if (studentBuilder_ == null) {
          if (dataCase_ == 7 &&
              data_ != cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.getDefaultInstance()) {
            data_ = cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.newBuilder((cyan.simple.protobuf.model.proto.StudentProto.StudentMessage) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 7) {
            studentBuilder_.mergeFrom(value);
          }
          studentBuilder_.setMessage(value);
        }
        dataCase_ = 7;
        return this;
      }
      /**
       * <pre>
       * 单个学生信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.StudentMessage student = 7;</code>
       */
      public Builder clearStudent() {
        if (studentBuilder_ == null) {
          if (dataCase_ == 7) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 7) {
            dataCase_ = 0;
            data_ = null;
          }
          studentBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 单个学生信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.StudentMessage student = 7;</code>
       */
      public cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder getStudentBuilder() {
        return getStudentFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 单个学生信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.StudentMessage student = 7;</code>
       */
      public cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder getStudentOrBuilder() {
        if ((dataCase_ == 7) && (studentBuilder_ != null)) {
          return studentBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 7) {
            return (cyan.simple.protobuf.model.proto.StudentProto.StudentMessage) data_;
          }
          return cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 单个学生信息
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.StudentMessage student = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cyan.simple.protobuf.model.proto.StudentProto.StudentMessage, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder, cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder> 
          getStudentFieldBuilder() {
        if (studentBuilder_ == null) {
          if (!(dataCase_ == 7)) {
            data_ = cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.getDefaultInstance();
          }
          studentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cyan.simple.protobuf.model.proto.StudentProto.StudentMessage, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder, cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder>(
                  (cyan.simple.protobuf.model.proto.StudentProto.StudentMessage) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 7;
        onChanged();;
        return studentBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage, cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.Builder, cyan.simple.protobuf.model.proto.StudentProto.StudentsMessageOrBuilder> studentsBuilder_;
      /**
       * <pre>
       * 这里没办法直接写 repeated TeacherMessage teachers = 8;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.StudentsMessage students = 8;</code>
       */
      public boolean hasStudents() {
        return dataCase_ == 8;
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated TeacherMessage teachers = 8;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.StudentsMessage students = 8;</code>
       */
      public cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage getStudents() {
        if (studentsBuilder_ == null) {
          if (dataCase_ == 8) {
            return (cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage) data_;
          }
          return cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.getDefaultInstance();
        } else {
          if (dataCase_ == 8) {
            return studentsBuilder_.getMessage();
          }
          return cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated TeacherMessage teachers = 8;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.StudentsMessage students = 8;</code>
       */
      public Builder setStudents(cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          studentsBuilder_.setMessage(value);
        }
        dataCase_ = 8;
        return this;
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated TeacherMessage teachers = 8;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.StudentsMessage students = 8;</code>
       */
      public Builder setStudents(
          cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          studentsBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 8;
        return this;
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated TeacherMessage teachers = 8;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.StudentsMessage students = 8;</code>
       */
      public Builder mergeStudents(cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage value) {
        if (studentsBuilder_ == null) {
          if (dataCase_ == 8 &&
              data_ != cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.getDefaultInstance()) {
            data_ = cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.newBuilder((cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 8) {
            studentsBuilder_.mergeFrom(value);
          }
          studentsBuilder_.setMessage(value);
        }
        dataCase_ = 8;
        return this;
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated TeacherMessage teachers = 8;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.StudentsMessage students = 8;</code>
       */
      public Builder clearStudents() {
        if (studentsBuilder_ == null) {
          if (dataCase_ == 8) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 8) {
            dataCase_ = 0;
            data_ = null;
          }
          studentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated TeacherMessage teachers = 8;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.StudentsMessage students = 8;</code>
       */
      public cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.Builder getStudentsBuilder() {
        return getStudentsFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated TeacherMessage teachers = 8;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.StudentsMessage students = 8;</code>
       */
      public cyan.simple.protobuf.model.proto.StudentProto.StudentsMessageOrBuilder getStudentsOrBuilder() {
        if ((dataCase_ == 8) && (studentsBuilder_ != null)) {
          return studentsBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 8) {
            return (cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage) data_;
          }
          return cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 这里没办法直接写 repeated TeacherMessage teachers = 8;
       * 需要在外部包装一层对象
       * </pre>
       *
       * <code>.cyan.simple.protobuf.proto.StudentsMessage students = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage, cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.Builder, cyan.simple.protobuf.model.proto.StudentProto.StudentsMessageOrBuilder> 
          getStudentsFieldBuilder() {
        if (studentsBuilder_ == null) {
          if (!(dataCase_ == 8)) {
            data_ = cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.getDefaultInstance();
          }
          studentsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage, cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.Builder, cyan.simple.protobuf.model.proto.StudentProto.StudentsMessageOrBuilder>(
                  (cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 8;
        onChanged();;
        return studentsBuilder_;
      }

      private long timestamp_ ;
      /**
       * <pre>
       * 时间
       * </pre>
       *
       * <code>int64 timestamp = 9;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * 时间
       * </pre>
       *
       * <code>int64 timestamp = 9;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 时间
       * </pre>
       *
       * <code>int64 timestamp = 9;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cyan.simple.protobuf.proto.ResultMessage)
    }

    // @@protoc_insertion_point(class_scope:cyan.simple.protobuf.proto.ResultMessage)
    private static final cyan.simple.protobuf.model.proto.ResultProto.ResultMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cyan.simple.protobuf.model.proto.ResultProto.ResultMessage();
    }

    public static cyan.simple.protobuf.model.proto.ResultProto.ResultMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResultMessage>
        PARSER = new com.google.protobuf.AbstractParser<ResultMessage>() {
      public ResultMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResultMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResultMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResultMessage> getParserForType() {
      return PARSER;
    }

    public cyan.simple.protobuf.model.proto.ResultProto.ResultMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cyan_simple_protobuf_proto_ResultMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cyan_simple_protobuf_proto_ResultMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ResultProto.proto\022\032cyan.simple.protobu" +
      "f.proto\032\020ClassProto.proto\032\022TeacherProto." +
      "proto\032\022StudentProto.proto\"\305\003\n\rResultMess" +
      "age\022\016\n\006status\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\0229\n\005" +
      "class\030\003 \001(\0132(.cyan.simple.protobuf.proto" +
      ".ClassMessageH\000\022=\n\007classes\030\004 \001(\0132*.cyan." +
      "simple.protobuf.proto.ClassesMessageH\000\022=" +
      "\n\007teacher\030\005 \001(\0132*.cyan.simple.protobuf.p" +
      "roto.TeacherMessageH\000\022?\n\010teachers\030\006 \001(\0132" +
      "+.cyan.simple.protobuf.proto.TeachersMes",
      "sageH\000\022=\n\007student\030\007 \001(\0132*.cyan.simple.pr" +
      "otobuf.proto.StudentMessageH\000\022?\n\010student" +
      "s\030\010 \001(\0132+.cyan.simple.protobuf.proto.Stu" +
      "dentsMessageH\000\022\021\n\ttimestamp\030\t \001(\003B\006\n\004dat" +
      "aB/\n cyan.simple.protobuf.model.protoB\013R" +
      "esultProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cyan.simple.protobuf.model.proto.ClassProto.getDescriptor(),
          cyan.simple.protobuf.model.proto.TeacherProto.getDescriptor(),
          cyan.simple.protobuf.model.proto.StudentProto.getDescriptor(),
        }, assigner);
    internal_static_cyan_simple_protobuf_proto_ResultMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cyan_simple_protobuf_proto_ResultMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cyan_simple_protobuf_proto_ResultMessage_descriptor,
        new java.lang.String[] { "Status", "Message", "Class_", "Classes", "Teacher", "Teachers", "Student", "Students", "Timestamp", "Data", });
    cyan.simple.protobuf.model.proto.ClassProto.getDescriptor();
    cyan.simple.protobuf.model.proto.TeacherProto.getDescriptor();
    cyan.simple.protobuf.model.proto.StudentProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
