// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StudentProto.proto

package cyan.simple.protobuf.model.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StudentsMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cyan.simple.protobuf.proto.StudentsMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
     */
    java.util.List<cyan.simple.protobuf.model.proto.StudentProto.StudentMessage> 
        getStudentsList();
    /**
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
     */
    cyan.simple.protobuf.model.proto.StudentProto.StudentMessage getStudents(int index);
    /**
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
     */
    int getStudentsCount();
    /**
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
     */
    java.util.List<? extends cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder> 
        getStudentsOrBuilderList();
    /**
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
     */
    cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder getStudentsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code cyan.simple.protobuf.proto.StudentsMessage}
   */
  public  static final class StudentsMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cyan.simple.protobuf.proto.StudentsMessage)
      StudentsMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StudentsMessage.newBuilder() to construct.
    private StudentsMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StudentsMessage() {
      students_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StudentsMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                students_ = new java.util.ArrayList<cyan.simple.protobuf.model.proto.StudentProto.StudentMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              students_.add(
                  input.readMessage(cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          students_ = java.util.Collections.unmodifiableList(students_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cyan.simple.protobuf.model.proto.StudentProto.internal_static_cyan_simple_protobuf_proto_StudentsMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cyan.simple.protobuf.model.proto.StudentProto.internal_static_cyan_simple_protobuf_proto_StudentsMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.class, cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.Builder.class);
    }

    public static final int STUDENTS_FIELD_NUMBER = 1;
    private java.util.List<cyan.simple.protobuf.model.proto.StudentProto.StudentMessage> students_;
    /**
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
     */
    public java.util.List<cyan.simple.protobuf.model.proto.StudentProto.StudentMessage> getStudentsList() {
      return students_;
    }
    /**
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
     */
    public java.util.List<? extends cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder> 
        getStudentsOrBuilderList() {
      return students_;
    }
    /**
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
     */
    public int getStudentsCount() {
      return students_.size();
    }
    /**
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
     */
    public cyan.simple.protobuf.model.proto.StudentProto.StudentMessage getStudents(int index) {
      return students_.get(index);
    }
    /**
     * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
     */
    public cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder getStudentsOrBuilder(
        int index) {
      return students_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < students_.size(); i++) {
        output.writeMessage(1, students_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < students_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, students_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage)) {
        return super.equals(obj);
      }
      cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage other = (cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage) obj;

      boolean result = true;
      result = result && getStudentsList()
          .equals(other.getStudentsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getStudentsCount() > 0) {
        hash = (37 * hash) + STUDENTS_FIELD_NUMBER;
        hash = (53 * hash) + getStudentsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cyan.simple.protobuf.proto.StudentsMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cyan.simple.protobuf.proto.StudentsMessage)
        cyan.simple.protobuf.model.proto.StudentProto.StudentsMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cyan.simple.protobuf.model.proto.StudentProto.internal_static_cyan_simple_protobuf_proto_StudentsMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cyan.simple.protobuf.model.proto.StudentProto.internal_static_cyan_simple_protobuf_proto_StudentsMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.class, cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.Builder.class);
      }

      // Construct using cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStudentsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (studentsBuilder_ == null) {
          students_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          studentsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cyan.simple.protobuf.model.proto.StudentProto.internal_static_cyan_simple_protobuf_proto_StudentsMessage_descriptor;
      }

      public cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage getDefaultInstanceForType() {
        return cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.getDefaultInstance();
      }

      public cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage build() {
        cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage buildPartial() {
        cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage result = new cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage(this);
        int from_bitField0_ = bitField0_;
        if (studentsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            students_ = java.util.Collections.unmodifiableList(students_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.students_ = students_;
        } else {
          result.students_ = studentsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage) {
          return mergeFrom((cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage other) {
        if (other == cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage.getDefaultInstance()) return this;
        if (studentsBuilder_ == null) {
          if (!other.students_.isEmpty()) {
            if (students_.isEmpty()) {
              students_ = other.students_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStudentsIsMutable();
              students_.addAll(other.students_);
            }
            onChanged();
          }
        } else {
          if (!other.students_.isEmpty()) {
            if (studentsBuilder_.isEmpty()) {
              studentsBuilder_.dispose();
              studentsBuilder_ = null;
              students_ = other.students_;
              bitField0_ = (bitField0_ & ~0x00000001);
              studentsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStudentsFieldBuilder() : null;
            } else {
              studentsBuilder_.addAllMessages(other.students_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<cyan.simple.protobuf.model.proto.StudentProto.StudentMessage> students_ =
        java.util.Collections.emptyList();
      private void ensureStudentsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          students_ = new java.util.ArrayList<cyan.simple.protobuf.model.proto.StudentProto.StudentMessage>(students_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cyan.simple.protobuf.model.proto.StudentProto.StudentMessage, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder, cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder> studentsBuilder_;

      /**
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
       */
      public java.util.List<cyan.simple.protobuf.model.proto.StudentProto.StudentMessage> getStudentsList() {
        if (studentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(students_);
        } else {
          return studentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
       */
      public int getStudentsCount() {
        if (studentsBuilder_ == null) {
          return students_.size();
        } else {
          return studentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
       */
      public cyan.simple.protobuf.model.proto.StudentProto.StudentMessage getStudents(int index) {
        if (studentsBuilder_ == null) {
          return students_.get(index);
        } else {
          return studentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
       */
      public Builder setStudents(
          int index, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.set(index, value);
          onChanged();
        } else {
          studentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
       */
      public Builder setStudents(
          int index, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.set(index, builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
       */
      public Builder addStudents(cyan.simple.protobuf.model.proto.StudentProto.StudentMessage value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.add(value);
          onChanged();
        } else {
          studentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
       */
      public Builder addStudents(
          int index, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.add(index, value);
          onChanged();
        } else {
          studentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
       */
      public Builder addStudents(
          cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.add(builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
       */
      public Builder addStudents(
          int index, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.add(index, builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
       */
      public Builder addAllStudents(
          java.lang.Iterable<? extends cyan.simple.protobuf.model.proto.StudentProto.StudentMessage> values) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, students_);
          onChanged();
        } else {
          studentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
       */
      public Builder clearStudents() {
        if (studentsBuilder_ == null) {
          students_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          studentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
       */
      public Builder removeStudents(int index) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.remove(index);
          onChanged();
        } else {
          studentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
       */
      public cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder getStudentsBuilder(
          int index) {
        return getStudentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
       */
      public cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder getStudentsOrBuilder(
          int index) {
        if (studentsBuilder_ == null) {
          return students_.get(index);  } else {
          return studentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
       */
      public java.util.List<? extends cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder> 
           getStudentsOrBuilderList() {
        if (studentsBuilder_ != null) {
          return studentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(students_);
        }
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
       */
      public cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder addStudentsBuilder() {
        return getStudentsFieldBuilder().addBuilder(
            cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
       */
      public cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder addStudentsBuilder(
          int index) {
        return getStudentsFieldBuilder().addBuilder(
            index, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.StudentMessage students = 1;</code>
       */
      public java.util.List<cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder> 
           getStudentsBuilderList() {
        return getStudentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cyan.simple.protobuf.model.proto.StudentProto.StudentMessage, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder, cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder> 
          getStudentsFieldBuilder() {
        if (studentsBuilder_ == null) {
          studentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cyan.simple.protobuf.model.proto.StudentProto.StudentMessage, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder, cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder>(
                  students_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          students_ = null;
        }
        return studentsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cyan.simple.protobuf.proto.StudentsMessage)
    }

    // @@protoc_insertion_point(class_scope:cyan.simple.protobuf.proto.StudentsMessage)
    private static final cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage();
    }

    public static cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StudentsMessage>
        PARSER = new com.google.protobuf.AbstractParser<StudentsMessage>() {
      public StudentsMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StudentsMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StudentsMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StudentsMessage> getParserForType() {
      return PARSER;
    }

    public cyan.simple.protobuf.model.proto.StudentProto.StudentsMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StudentMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cyan.simple.protobuf.proto.StudentMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 年龄
     * </pre>
     *
     * <code>int32 age = 2;</code>
     */
    int getAge();

    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>string sex = 3;</code>
     */
    java.lang.String getSex();
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>string sex = 3;</code>
     */
    com.google.protobuf.ByteString
        getSexBytes();
  }
  /**
   * Protobuf type {@code cyan.simple.protobuf.proto.StudentMessage}
   */
  public  static final class StudentMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cyan.simple.protobuf.proto.StudentMessage)
      StudentMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StudentMessage.newBuilder() to construct.
    private StudentMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StudentMessage() {
      name_ = "";
      age_ = 0;
      sex_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StudentMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              sex_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cyan.simple.protobuf.model.proto.StudentProto.internal_static_cyan_simple_protobuf_proto_StudentMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cyan.simple.protobuf.model.proto.StudentProto.internal_static_cyan_simple_protobuf_proto_StudentMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.class, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <pre>
     * 年龄
     * </pre>
     *
     * <code>int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int SEX_FIELD_NUMBER = 3;
    private volatile java.lang.Object sex_;
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>string sex = 3;</code>
     */
    public java.lang.String getSex() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sex_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>string sex = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSexBytes() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      if (!getSexBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sex_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (!getSexBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sex_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cyan.simple.protobuf.model.proto.StudentProto.StudentMessage)) {
        return super.equals(obj);
      }
      cyan.simple.protobuf.model.proto.StudentProto.StudentMessage other = (cyan.simple.protobuf.model.proto.StudentProto.StudentMessage) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getAge()
          == other.getAge());
      result = result && getSex()
          .equals(other.getSex());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + getSex().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cyan.simple.protobuf.model.proto.StudentProto.StudentMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.StudentProto.StudentMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cyan.simple.protobuf.model.proto.StudentProto.StudentMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cyan.simple.protobuf.proto.StudentMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cyan.simple.protobuf.proto.StudentMessage)
        cyan.simple.protobuf.model.proto.StudentProto.StudentMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cyan.simple.protobuf.model.proto.StudentProto.internal_static_cyan_simple_protobuf_proto_StudentMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cyan.simple.protobuf.model.proto.StudentProto.internal_static_cyan_simple_protobuf_proto_StudentMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.class, cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.Builder.class);
      }

      // Construct using cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        sex_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cyan.simple.protobuf.model.proto.StudentProto.internal_static_cyan_simple_protobuf_proto_StudentMessage_descriptor;
      }

      public cyan.simple.protobuf.model.proto.StudentProto.StudentMessage getDefaultInstanceForType() {
        return cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.getDefaultInstance();
      }

      public cyan.simple.protobuf.model.proto.StudentProto.StudentMessage build() {
        cyan.simple.protobuf.model.proto.StudentProto.StudentMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cyan.simple.protobuf.model.proto.StudentProto.StudentMessage buildPartial() {
        cyan.simple.protobuf.model.proto.StudentProto.StudentMessage result = new cyan.simple.protobuf.model.proto.StudentProto.StudentMessage(this);
        result.name_ = name_;
        result.age_ = age_;
        result.sex_ = sex_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cyan.simple.protobuf.model.proto.StudentProto.StudentMessage) {
          return mergeFrom((cyan.simple.protobuf.model.proto.StudentProto.StudentMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cyan.simple.protobuf.model.proto.StudentProto.StudentMessage other) {
        if (other == cyan.simple.protobuf.model.proto.StudentProto.StudentMessage.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.getSex().isEmpty()) {
          sex_ = other.sex_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cyan.simple.protobuf.model.proto.StudentProto.StudentMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cyan.simple.protobuf.model.proto.StudentProto.StudentMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <pre>
       * 年龄
       * </pre>
       *
       * <code>int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <pre>
       * 年龄
       * </pre>
       *
       * <code>int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 年龄
       * </pre>
       *
       * <code>int32 age = 2;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sex_ = "";
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>string sex = 3;</code>
       */
      public java.lang.String getSex() {
        java.lang.Object ref = sex_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sex_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>string sex = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSexBytes() {
        java.lang.Object ref = sex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>string sex = 3;</code>
       */
      public Builder setSex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>string sex = 3;</code>
       */
      public Builder clearSex() {
        
        sex_ = getDefaultInstance().getSex();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>string sex = 3;</code>
       */
      public Builder setSexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sex_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cyan.simple.protobuf.proto.StudentMessage)
    }

    // @@protoc_insertion_point(class_scope:cyan.simple.protobuf.proto.StudentMessage)
    private static final cyan.simple.protobuf.model.proto.StudentProto.StudentMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cyan.simple.protobuf.model.proto.StudentProto.StudentMessage();
    }

    public static cyan.simple.protobuf.model.proto.StudentProto.StudentMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StudentMessage>
        PARSER = new com.google.protobuf.AbstractParser<StudentMessage>() {
      public StudentMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StudentMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StudentMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StudentMessage> getParserForType() {
      return PARSER;
    }

    public cyan.simple.protobuf.model.proto.StudentProto.StudentMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cyan_simple_protobuf_proto_StudentsMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cyan_simple_protobuf_proto_StudentsMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cyan_simple_protobuf_proto_StudentMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cyan_simple_protobuf_proto_StudentMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022StudentProto.proto\022\032cyan.simple.protob" +
      "uf.proto\"O\n\017StudentsMessage\022<\n\010students\030" +
      "\001 \003(\0132*.cyan.simple.protobuf.proto.Stude" +
      "ntMessage\"8\n\016StudentMessage\022\014\n\004name\030\001 \001(" +
      "\t\022\013\n\003age\030\002 \001(\005\022\013\n\003sex\030\003 \001(\tB0\n cyan.simp" +
      "le.protobuf.model.protoB\014StudentProtob\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cyan_simple_protobuf_proto_StudentsMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cyan_simple_protobuf_proto_StudentsMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cyan_simple_protobuf_proto_StudentsMessage_descriptor,
        new java.lang.String[] { "Students", });
    internal_static_cyan_simple_protobuf_proto_StudentMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cyan_simple_protobuf_proto_StudentMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cyan_simple_protobuf_proto_StudentMessage_descriptor,
        new java.lang.String[] { "Name", "Age", "Sex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
