// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TeacherProto.proto

package cyan.simple.protobuf.model.proto;

public final class TeacherProto {
  private TeacherProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TeachersMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cyan.simple.protobuf.proto.TeachersMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
     */
    java.util.List<cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage> 
        getTeachersList();
    /**
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
     */
    cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage getTeachers(int index);
    /**
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
     */
    int getTeachersCount();
    /**
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
     */
    java.util.List<? extends cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder> 
        getTeachersOrBuilderList();
    /**
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
     */
    cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder getTeachersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code cyan.simple.protobuf.proto.TeachersMessage}
   */
  public  static final class TeachersMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cyan.simple.protobuf.proto.TeachersMessage)
      TeachersMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TeachersMessage.newBuilder() to construct.
    private TeachersMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TeachersMessage() {
      teachers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TeachersMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                teachers_ = new java.util.ArrayList<cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              teachers_.add(
                  input.readMessage(cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          teachers_ = java.util.Collections.unmodifiableList(teachers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cyan.simple.protobuf.model.proto.TeacherProto.internal_static_cyan_simple_protobuf_proto_TeachersMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cyan.simple.protobuf.model.proto.TeacherProto.internal_static_cyan_simple_protobuf_proto_TeachersMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.class, cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.Builder.class);
    }

    public static final int TEACHERS_FIELD_NUMBER = 1;
    private java.util.List<cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage> teachers_;
    /**
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
     */
    public java.util.List<cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage> getTeachersList() {
      return teachers_;
    }
    /**
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
     */
    public java.util.List<? extends cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder> 
        getTeachersOrBuilderList() {
      return teachers_;
    }
    /**
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
     */
    public int getTeachersCount() {
      return teachers_.size();
    }
    /**
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
     */
    public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage getTeachers(int index) {
      return teachers_.get(index);
    }
    /**
     * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
     */
    public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder getTeachersOrBuilder(
        int index) {
      return teachers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < teachers_.size(); i++) {
        output.writeMessage(1, teachers_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < teachers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, teachers_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage)) {
        return super.equals(obj);
      }
      cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage other = (cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage) obj;

      boolean result = true;
      result = result && getTeachersList()
          .equals(other.getTeachersList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTeachersCount() > 0) {
        hash = (37 * hash) + TEACHERS_FIELD_NUMBER;
        hash = (53 * hash) + getTeachersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cyan.simple.protobuf.proto.TeachersMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cyan.simple.protobuf.proto.TeachersMessage)
        cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cyan.simple.protobuf.model.proto.TeacherProto.internal_static_cyan_simple_protobuf_proto_TeachersMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cyan.simple.protobuf.model.proto.TeacherProto.internal_static_cyan_simple_protobuf_proto_TeachersMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.class, cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.Builder.class);
      }

      // Construct using cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTeachersFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (teachersBuilder_ == null) {
          teachers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          teachersBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cyan.simple.protobuf.model.proto.TeacherProto.internal_static_cyan_simple_protobuf_proto_TeachersMessage_descriptor;
      }

      public cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage getDefaultInstanceForType() {
        return cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.getDefaultInstance();
      }

      public cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage build() {
        cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage buildPartial() {
        cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage result = new cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage(this);
        int from_bitField0_ = bitField0_;
        if (teachersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            teachers_ = java.util.Collections.unmodifiableList(teachers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.teachers_ = teachers_;
        } else {
          result.teachers_ = teachersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage) {
          return mergeFrom((cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage other) {
        if (other == cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage.getDefaultInstance()) return this;
        if (teachersBuilder_ == null) {
          if (!other.teachers_.isEmpty()) {
            if (teachers_.isEmpty()) {
              teachers_ = other.teachers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTeachersIsMutable();
              teachers_.addAll(other.teachers_);
            }
            onChanged();
          }
        } else {
          if (!other.teachers_.isEmpty()) {
            if (teachersBuilder_.isEmpty()) {
              teachersBuilder_.dispose();
              teachersBuilder_ = null;
              teachers_ = other.teachers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              teachersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTeachersFieldBuilder() : null;
            } else {
              teachersBuilder_.addAllMessages(other.teachers_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage> teachers_ =
        java.util.Collections.emptyList();
      private void ensureTeachersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          teachers_ = new java.util.ArrayList<cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage>(teachers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder> teachersBuilder_;

      /**
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
       */
      public java.util.List<cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage> getTeachersList() {
        if (teachersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(teachers_);
        } else {
          return teachersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
       */
      public int getTeachersCount() {
        if (teachersBuilder_ == null) {
          return teachers_.size();
        } else {
          return teachersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
       */
      public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage getTeachers(int index) {
        if (teachersBuilder_ == null) {
          return teachers_.get(index);
        } else {
          return teachersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
       */
      public Builder setTeachers(
          int index, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage value) {
        if (teachersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeachersIsMutable();
          teachers_.set(index, value);
          onChanged();
        } else {
          teachersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
       */
      public Builder setTeachers(
          int index, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder builderForValue) {
        if (teachersBuilder_ == null) {
          ensureTeachersIsMutable();
          teachers_.set(index, builderForValue.build());
          onChanged();
        } else {
          teachersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
       */
      public Builder addTeachers(cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage value) {
        if (teachersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeachersIsMutable();
          teachers_.add(value);
          onChanged();
        } else {
          teachersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
       */
      public Builder addTeachers(
          int index, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage value) {
        if (teachersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeachersIsMutable();
          teachers_.add(index, value);
          onChanged();
        } else {
          teachersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
       */
      public Builder addTeachers(
          cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder builderForValue) {
        if (teachersBuilder_ == null) {
          ensureTeachersIsMutable();
          teachers_.add(builderForValue.build());
          onChanged();
        } else {
          teachersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
       */
      public Builder addTeachers(
          int index, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder builderForValue) {
        if (teachersBuilder_ == null) {
          ensureTeachersIsMutable();
          teachers_.add(index, builderForValue.build());
          onChanged();
        } else {
          teachersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
       */
      public Builder addAllTeachers(
          java.lang.Iterable<? extends cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage> values) {
        if (teachersBuilder_ == null) {
          ensureTeachersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, teachers_);
          onChanged();
        } else {
          teachersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
       */
      public Builder clearTeachers() {
        if (teachersBuilder_ == null) {
          teachers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          teachersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
       */
      public Builder removeTeachers(int index) {
        if (teachersBuilder_ == null) {
          ensureTeachersIsMutable();
          teachers_.remove(index);
          onChanged();
        } else {
          teachersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
       */
      public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder getTeachersBuilder(
          int index) {
        return getTeachersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
       */
      public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder getTeachersOrBuilder(
          int index) {
        if (teachersBuilder_ == null) {
          return teachers_.get(index);  } else {
          return teachersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
       */
      public java.util.List<? extends cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder> 
           getTeachersOrBuilderList() {
        if (teachersBuilder_ != null) {
          return teachersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(teachers_);
        }
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
       */
      public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder addTeachersBuilder() {
        return getTeachersFieldBuilder().addBuilder(
            cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
       */
      public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder addTeachersBuilder(
          int index) {
        return getTeachersFieldBuilder().addBuilder(
            index, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .cyan.simple.protobuf.proto.TeacherMessage teachers = 1;</code>
       */
      public java.util.List<cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder> 
           getTeachersBuilderList() {
        return getTeachersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder> 
          getTeachersFieldBuilder() {
        if (teachersBuilder_ == null) {
          teachersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder>(
                  teachers_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          teachers_ = null;
        }
        return teachersBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cyan.simple.protobuf.proto.TeachersMessage)
    }

    // @@protoc_insertion_point(class_scope:cyan.simple.protobuf.proto.TeachersMessage)
    private static final cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage();
    }

    public static cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TeachersMessage>
        PARSER = new com.google.protobuf.AbstractParser<TeachersMessage>() {
      public TeachersMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TeachersMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TeachersMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TeachersMessage> getParserForType() {
      return PARSER;
    }

    public cyan.simple.protobuf.model.proto.TeacherProto.TeachersMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TeacherMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cyan.simple.protobuf.proto.TeacherMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 年龄
     * </pre>
     *
     * <code>int32 age = 2;</code>
     */
    int getAge();

    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>string sex = 3;</code>
     */
    java.lang.String getSex();
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>string sex = 3;</code>
     */
    com.google.protobuf.ByteString
        getSexBytes();

    /**
     * <pre>
     * 学科
     * </pre>
     *
     * <code>string subject = 4;</code>
     */
    java.lang.String getSubject();
    /**
     * <pre>
     * 学科
     * </pre>
     *
     * <code>string subject = 4;</code>
     */
    com.google.protobuf.ByteString
        getSubjectBytes();
  }
  /**
   * Protobuf type {@code cyan.simple.protobuf.proto.TeacherMessage}
   */
  public  static final class TeacherMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cyan.simple.protobuf.proto.TeacherMessage)
      TeacherMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TeacherMessage.newBuilder() to construct.
    private TeacherMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TeacherMessage() {
      name_ = "";
      age_ = 0;
      sex_ = "";
      subject_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TeacherMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              sex_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              subject_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cyan.simple.protobuf.model.proto.TeacherProto.internal_static_cyan_simple_protobuf_proto_TeacherMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cyan.simple.protobuf.model.proto.TeacherProto.internal_static_cyan_simple_protobuf_proto_TeacherMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.class, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <pre>
     * 年龄
     * </pre>
     *
     * <code>int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int SEX_FIELD_NUMBER = 3;
    private volatile java.lang.Object sex_;
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>string sex = 3;</code>
     */
    public java.lang.String getSex() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sex_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>string sex = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSexBytes() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBJECT_FIELD_NUMBER = 4;
    private volatile java.lang.Object subject_;
    /**
     * <pre>
     * 学科
     * </pre>
     *
     * <code>string subject = 4;</code>
     */
    public java.lang.String getSubject() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subject_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 学科
     * </pre>
     *
     * <code>string subject = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      if (!getSexBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sex_);
      }
      if (!getSubjectBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, subject_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (!getSexBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sex_);
      }
      if (!getSubjectBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, subject_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage)) {
        return super.equals(obj);
      }
      cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage other = (cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getAge()
          == other.getAge());
      result = result && getSex()
          .equals(other.getSex());
      result = result && getSubject()
          .equals(other.getSubject());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + getSex().hashCode();
      hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getSubject().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cyan.simple.protobuf.proto.TeacherMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cyan.simple.protobuf.proto.TeacherMessage)
        cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cyan.simple.protobuf.model.proto.TeacherProto.internal_static_cyan_simple_protobuf_proto_TeacherMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cyan.simple.protobuf.model.proto.TeacherProto.internal_static_cyan_simple_protobuf_proto_TeacherMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.class, cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.Builder.class);
      }

      // Construct using cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        sex_ = "";

        subject_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cyan.simple.protobuf.model.proto.TeacherProto.internal_static_cyan_simple_protobuf_proto_TeacherMessage_descriptor;
      }

      public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage getDefaultInstanceForType() {
        return cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.getDefaultInstance();
      }

      public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage build() {
        cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage buildPartial() {
        cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage result = new cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage(this);
        result.name_ = name_;
        result.age_ = age_;
        result.sex_ = sex_;
        result.subject_ = subject_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage) {
          return mergeFrom((cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage other) {
        if (other == cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.getSex().isEmpty()) {
          sex_ = other.sex_;
          onChanged();
        }
        if (!other.getSubject().isEmpty()) {
          subject_ = other.subject_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <pre>
       * 年龄
       * </pre>
       *
       * <code>int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <pre>
       * 年龄
       * </pre>
       *
       * <code>int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 年龄
       * </pre>
       *
       * <code>int32 age = 2;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sex_ = "";
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>string sex = 3;</code>
       */
      public java.lang.String getSex() {
        java.lang.Object ref = sex_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sex_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>string sex = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSexBytes() {
        java.lang.Object ref = sex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>string sex = 3;</code>
       */
      public Builder setSex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>string sex = 3;</code>
       */
      public Builder clearSex() {
        
        sex_ = getDefaultInstance().getSex();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>string sex = 3;</code>
       */
      public Builder setSexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sex_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object subject_ = "";
      /**
       * <pre>
       * 学科
       * </pre>
       *
       * <code>string subject = 4;</code>
       */
      public java.lang.String getSubject() {
        java.lang.Object ref = subject_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subject_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 学科
       * </pre>
       *
       * <code>string subject = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSubjectBytes() {
        java.lang.Object ref = subject_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subject_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 学科
       * </pre>
       *
       * <code>string subject = 4;</code>
       */
      public Builder setSubject(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subject_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 学科
       * </pre>
       *
       * <code>string subject = 4;</code>
       */
      public Builder clearSubject() {
        
        subject_ = getDefaultInstance().getSubject();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 学科
       * </pre>
       *
       * <code>string subject = 4;</code>
       */
      public Builder setSubjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subject_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cyan.simple.protobuf.proto.TeacherMessage)
    }

    // @@protoc_insertion_point(class_scope:cyan.simple.protobuf.proto.TeacherMessage)
    private static final cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage();
    }

    public static cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TeacherMessage>
        PARSER = new com.google.protobuf.AbstractParser<TeacherMessage>() {
      public TeacherMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TeacherMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TeacherMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TeacherMessage> getParserForType() {
      return PARSER;
    }

    public cyan.simple.protobuf.model.proto.TeacherProto.TeacherMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cyan_simple_protobuf_proto_TeachersMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cyan_simple_protobuf_proto_TeachersMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cyan_simple_protobuf_proto_TeacherMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cyan_simple_protobuf_proto_TeacherMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022TeacherProto.proto\022\032cyan.simple.protob" +
      "uf.proto\"O\n\017TeachersMessage\022<\n\010teachers\030" +
      "\001 \003(\0132*.cyan.simple.protobuf.proto.Teach" +
      "erMessage\"I\n\016TeacherMessage\022\014\n\004name\030\001 \001(" +
      "\t\022\013\n\003age\030\002 \001(\005\022\013\n\003sex\030\003 \001(\t\022\017\n\007subject\030\004" +
      " \001(\tB0\n cyan.simple.protobuf.model.proto" +
      "B\014TeacherProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cyan_simple_protobuf_proto_TeachersMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cyan_simple_protobuf_proto_TeachersMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cyan_simple_protobuf_proto_TeachersMessage_descriptor,
        new java.lang.String[] { "Teachers", });
    internal_static_cyan_simple_protobuf_proto_TeacherMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cyan_simple_protobuf_proto_TeacherMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cyan_simple_protobuf_proto_TeacherMessage_descriptor,
        new java.lang.String[] { "Name", "Age", "Sex", "Subject", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
